### ISSUE TITLE
UI - Individual Groups Page

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#10]
This page shows TEAM MEMBERS of a particular Group.
-
**USER INTERFACE**
- Search field for Adding Team Members
- ADD button
- Members list
- REMOVE button
- EDIT button (will redirect to user profile)

**FUNCTIONALITY**
- SEARCH and ADD
- REMOVE
- EDIT

Screenshot
-
![image](https://cloud.githubusercontent.com/assets/10201846/8296285/51d0a142-1981-11e5-92dd-9c37e53f375a.png)

**Comment by Jinsuke** [comment]
*Add MEMBERS AND CALENDAR TAB
*MEMBERS tab still has the same output
*Add CALENDAR Function that will show users who are on leave (Refer to Outlook's Calendar)

**Comment by Jinsuke** [comment]
UI - Individual Groups Page #10
INDIVIDUAL GROUP PAGE
-working links for NAMES and EDIT button

**Comment by Jinsuke** [comment]
150630 UPDATE

Members Tab
![image](https://cloud.githubusercontent.com/assets/10201846/8421809/16f23326-1f06-11e5-97e9-43c4a195307a.png)

Calendar Tab
![image](https://cloud.githubusercontent.com/assets/10201846/8421815/2136d508-1f06-11e5-86c9-33234de29472.png)

**Comment by chrisperez** [comment]
On groups/view/1 > Members Tab
---
- Adjust members list
- Change edit button to dark blue

![image](https://cloud.githubusercontent.com/assets/4833394/8421717/6457161e-1f05-11e5-978e-f5192aa69eca.png)

-----------

On groups/view/1 > Calendar Tab
---
- Removed Month, Week and Day View Buttons
- Move Month and Year to the right
- Remove style="width:200px" on Date Rang Picker under Select Date Range Box
- Change Status Picklist
- Change Submit Button's color to green and font case to Camel Case

![image](https://cloud.githubusercontent.com/assets/4833394/8421748/c3bad8c0-1f05-11e5-8d97-f0f2297bc4da.png)

**Comment by Jinsuke** [comment]
On Groups Calendar tab
--
- Removed ADD EVENT
- EVENT toggle is now on the bottom of the Calendar
- This will be a page for viewing status events only (no schedules).

![image](https://cloud.githubusercontent.com/assets/10201846/8448607/18a81d24-1ffc-11e5-8e3c-a8c3e96dffc3.png)
![image](https://cloud.githubusercontent.com/assets/10201846/8448611/1d36a270-1ffc-11e5-896b-1d22aaabd7c5.png)

**Comment by gigiadamantopoulos** [comment]
Hi,

Is it possible that when you click the calendar tab, the calendar will already be displayed instead of clicking the "today" button first??
![image](https://cloud.githubusercontent.com/assets/10202106/8462899/5ffcb30c-2069-11e5-9b96-a5e19121472d.png)

Also, the Events table should be below the calendar right?
![image](https://cloud.githubusercontent.com/assets/10202106/8462934/aee0c454-2069-11e5-9c67-1a477f2ae176.png)

**Comment by Jinsuke** [comment]
Calendar EVENT is now moved on the bottom of the tab.
--
![image](https://cloud.githubusercontent.com/assets/10201846/8468485/a52e2f60-209f-11e5-9f21-b4fae7710172.png)

Calendar's functionality (Including the today button is for Issue #30

**Comment by asjr4584** [comment]
Hi Jin,

Can you make the size of the calendar adjustable or responsive? I would like to know if the calendar can match the width of the Event tab.

**Comment by asjr4584** [comment]
I would like to see a responsive calendar in the groups:

![image](https://cloud.githubusercontent.com/assets/4827031/8472026/3fa4f8a0-20d0-11e5-956c-cdeee39d7c5e.png)

**Comment by Jinsuke** [comment]
Calendar's full UI (Including the today button and responsiveness is for Issue #29
-
**Changes in Groups/View**
Made Calendar width same as EVENTS Toggle.
![image](https://cloud.githubusercontent.com/assets/10201846/8490787/9e01559c-2161-11e5-8fa5-b16a97212686.png)

Calendar is already responsive. You can test it out by re-sizing the whole window.

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing, please.

**Comment by Jinsuke** [comment]
Updates
-
- Changed Tab Order [Calendar, Members]
- Calendar now appears (without clicking Today button)

![image](https://cloud.githubusercontent.com/assets/10201846/8498028/d1aaa3a0-21b4-11e5-9664-af4fa2097635.png)

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by Jinsuke** [comment]
:new: UPDATE
-
- Separate Calendar Page from Members page
- Member's page will now have Roles table category

**Comment by Jinsuke** [comment]
:new: Update 150716
-
- **Separate Pages for Calendar and Members Page**
![image](https://cloud.githubusercontent.com/assets/10201846/8716555/0b33e3b0-2bc5-11e5-9aaf-bd302a88fe13.png)

- **Roles are already included in the tables. Role entries is still ongoing**
![image](https://cloud.githubusercontent.com/assets/10201846/8716570/3c7d0ee2-2bc5-11e5-8d34-62d525379812.png)

**Comment by Jinsuke** [comment]
:new: Update
-
- Fixed active link for Individual Groups page

![image](https://cloud.githubusercontent.com/assets/10201846/8790782/7a00e2bc-2f84-11e5-8a06-428b2c4558c3.png)

**Comment by lyn2711** [comment]
Question:

What's the use of the "today" button under the Calendar tab?

**Comment by Jinsuke** [comment]
Hi Ms. @lyn2711 ,
 Today button is used when you want to go back to the current date. This is only clickable if you're navigating the calendar to other months. :smile:

**Comment by lyn2711** [comment]
Pass

**Comment by Jinsuke** [comment]
:new: Update
-
Member's page is now on Ascending Order.

![image](https://cloud.githubusercontent.com/assets/10201846/9265820/286744f6-426b-11e5-9ae0-a3c8fcfdc570.png)

**Comment by lyn2711** [comment]
Pass, test done in 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
