### ISSUE TITLE
Functionality: Broken Link from the Header

### ISSUE THREAD

**Issue by asjr4584** [HP-Corel/AttendanceTracker#105]
Issue
-
- Clicking the Attendance Tracker from the header shows an error page.

http://c9t16755.itcs.hpecorp.net/organization/

Can you fix this, please?
Thank you!

**Comment by asjr4584** [comment]
Deadline: December 15.

**Comment by Jinsuke** [comment]
Hi Sir @asjr4584,

- Upon testing, this seems to work fine. Can you tell me how you're able to access just the /organization/ page? Tried troubleshooting it and the link seems to work fine.

![image](https://cloud.githubusercontent.com/assets/10201846/11710820/022497fe-9f5d-11e5-90ad-00e7b4b69335.png)

**Comment by asjr4584** [comment]
@Jinsuke i did encounter that before, but now it seems working fine :)
