### ISSUE TITLE
Functionality - Individual Groups Page

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#11]
This page shows TEAM MEMBERS of a particular Group.
-
**USER INTERFACE**
- Search field for Adding Team Members
- ADD button
- Members list
- REMOVE button
- EDIT button (will redirect to user profile)

**FUNCTIONALITY**
- SEARCH and ADD
- REMOVE
- EDIT

Screenshot
-
![image](https://cloud.githubusercontent.com/assets/10201846/8296285/51d0a142-1981-11e5-92dd-9c37e53f375a.png)

**Comment by Jinsuke** [comment]
*Add MEMBERS AND CALENDAR TAB
*MEMBERS tab still has the same output
*Add CALENDAR Function that will show users who are on leave (Refer to Outlook's Calendar)

**Comment by chrisperez** [comment]
- Added filter in Individual Group Pages when Searching for members
- You can search a member by enter the Employee Number, Email, or Name

**Comment by gigiadamantopoulos** [comment]
No issues

**Comment by asjr4584** [comment]
@chrisperez is this now ready for testing? if so, please assign this now to @gigiadamantopoulos

**Comment by chrisperez** [comment]
@gigiadamantopoulos, For testing.

**Comment by gigiadamantopoulos** [comment]
Passed!

**Comment by Jinsuke** [comment]
:new: UPDATE 150715
-
- Separate Calendar Page from Members page
- Member's page will now have Roles table category for determining Supervisor role from Agents

**Comment by lyn2711** [comment]
When I am on the CS group, and I enter my employee number in the box (since it was mentioned that I can search for a member using the employee number), the page just refreshes but still shows the same content, no error messages or something.

**Comment by lyn2711** [comment]
Passed, test done in 203

**Comment by gigiadamantopoulos** [comment]
Passed in 201
