### ISSUE TITLE
Functionality -  Roles / User Group

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#12]
**NOTE: User Group tab should be changed to "User Role"**

**NOTE: LEVEL 1 has the lowest access. Level access is ascending.**
MANAGER - LEVEL 4
SUPERVISOR - LEVEL 3
TEAM LEAD - LEVEL 2
AGENT - LEVEL 1

FUNCTIONALITIES
-
* Hierarchy (Level selection)
* Add Group (add group role)
* Edit button
* Delete button (delete group role)
* Add Hierarchy (add new hierarchy)
* Delete button (delete hierarchy level)

**Reference MockUp**
![image](https://cloud.githubusercontent.com/assets/10201846/8296326/d6764c26-1981-11e5-983b-868cdeae8c73.png)

**Comment by asjr4584** [comment]
For now, let's focus on the two different accounts:

(1) Admin Accounts (Managers, Supervisors, Team Leads): Read & Write or Full Control
(2) Agent Accounts: View only

Later on we can further differentiate the roles of Admin accounts using Levels; example:

Level 4 Manager has Full Control; can create organization and view different organization
Level 3 Supervisors has Read & Write but cannot create and delete organization; can only view the organization he is within. etc.

**Comment by chrisperez** [comment]
- Removed Cancel Button on Adding Role
- Create individual view page for each role
- Role names on the role index page now have hyperlinks going to their respective view pages
- Calendar tab on individual role view page was removed.

**Comment by chrisperez** [comment]
- Added filter on Role's member search

**Comment by gigiadamantopoulos** [comment]
Must add a restriction here.

Is it possible that a member can have 2 roles at the same time? If not, this needs to reassure that each member can be added to only one role and will not be added in other roles.

**Comment by chrisperez** [comment]
Added field validation to required fields. Please merge and test

**Comment by asjr4584** [comment]
@chrisperez do we have now specific levels for each Role?

NOTE: LEVEL 1 has the lowest access. Level access is ascending.
MANAGER - LEVEL 4
SUPERVISOR - LEVEL 3
TEAM LEAD - LEVEL 2
AGENT - LEVEL 1

**Comment by chrisperez** [comment]
No, we still don't have this feature.

**Comment by chrisperez** [comment]
Can we create a new issue regarding hierarchy functions instead since this issue is for Roles?

**Comment by asjr4584** [comment]
@chrisperez yes please create a new issue and tag it to Milestone 2.

**Comment by chrisperez** [comment]
Please test the Role Page functionality if working.

- Check field validation upon creating a role and/or hierarchy.
- When you add a person in a role it will be save to that role.
- When you add the same person on another role, then that person will be included in that role. However, his name from the previous role will be removed.

**Comment by gigiadamantopoulos** [comment]
"When you add the same person on another role, then that person will be included in that role. However, his name from the previous role will be removed."

- Can we add like a notification or a pop-up alert that the person was removed to another role?

**Comment by asjr4584** [comment]
@chrisperez can you reply to this, please?

**Comment by alvincrisuycorel** [comment]
@gigiadamantopoulos this can be add in the future. 

Please create an issue regarding the notification/pop up alert

**Comment by gigiadamantopoulos** [comment]
Issue created https://github.com/HP-Corel/AttendanceTracker/issues/42

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Passed, test done in 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
