### ISSUE TITLE
Software - UI Additional Changes

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#13]
Task
-
* ALERT WINDOW should be on top.
* OVERBREAK ALERT time should be in RED Color.
* ALERT WINDOW should have at least 5 minutes notification before actual time lapses

**Note: We will PROVIDE Log-in details for agents to view information on the attendance tracker**

**Comment by asjr4584** [comment]
Add History button to the application that will allow the agent to view his/her employee's attendance history through a web browser.

However, he needs to sign in again since application and website have different sessions.

**Comment by Jinsuke** [comment]
Software UI Update
--
- Added View Records (History button)

![image](https://cloud.githubusercontent.com/assets/10201846/8449896/fc1b1164-2007-11e5-952a-e8846de4613e.png)

**Comment by asjr4584** [comment]
@alvincrisuycorel please refer to @gigiadamantopoulos mockup in the PowerPoint Presentation:

https://my.sharepoint.hp.com/my/asiapacific_salvadoa/_layouts/15/start.aspx#/Documents/Forms/All.aspx?RootFolder=%2fmy%2fasiapacific%5fsalvadoa%2fDocuments%2fAttendance%20Tracker%20Application%20Project&FolderCTID=0x0120007BCEA5205BA6C846870457F50EC214AB

**Comment by alvincrisuycorel** [comment]
Hi sir,

I did not change the color of the button rather I change the color of the running time label.

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing, please.

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel , I can't seem to test the software. It keeps on crashing when I open it. I'm using the latest version that you sent in my email.

![image](https://cloud.githubusercontent.com/assets/10202106/8503778/2ddee77a-21f7-11e5-81e4-57ee0825b265.png)

**Comment by gigiadamantopoulos** [comment]
Passed!

**Comment by lyn2711** [comment]
Program crashes

![image](https://cloud.githubusercontent.com/assets/7370325/8801603/86a1017c-2fee-11e5-8971-a091bd1bdcc2.png)

**Comment by alvincrisuycorel** [comment]
:disappointed:

**Comment by alvincrisuycorel** [comment]
Hi Ma'am Evs,

@lyn2711 

When did this happened?

When clicking a certain button like logout and different auxes or it just stop working?

**Comment by lyn2711** [comment]
Suggestion: Can we add background color to the application?

**Comment by alvincrisuycorel** [comment]
Yes po :smile: You can suggest what will it look like

**Comment by gigiadamantopoulos** [comment]
Minor Rev:

Change to ellipses if the name is too long so that the Logout button will not be blocked.
![image](https://cloud.githubusercontent.com/assets/10202106/9054594/aabe8eea-3ab5-11e5-81e5-15375ed81e6a.png)

**Comment by alvincrisuycorel** [comment]
- Adding popup when changing status of the user.

**Comment by alvincrisuycorel** [comment]
Hi Gigi 

@gigiadamantopoulos 

please check if the message is fine when changing the status of the user :smile:

**Comment by gigiadamantopoulos** [comment]
It's ok now @alvincrisuycorel thanks!

**Comment by lyn2711** [comment]
Passed, test done in 203

**Comment by gigiadamantopoulos** [comment]
Passed in 201
