### ISSUE TITLE
UI - Dashboard Page

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#14]
*Add TARDINESS tab that will show the running time for lates once the actual shift has started.

Reference (Add the Tardiness Tab after STATUS)
![image](https://cloud.githubusercontent.com/assets/10201846/8301130/ea998c36-19bd-11e5-93c0-3055a161d95a.png)

**Comment by Jinsuke** [comment]
*TITLE TAB will be removed

*Add ON DESK tab (has 2 columns)
   -AUX 7
   -SHORTBREAK
Note: ONDESK should total to 8hrs

*Add LONGBREAK tab

**Comment by Jinsuke** [comment]
Dashboard UI Update
--
- Added MEETING/ON DESK/LUNCH/TARDINESS/FLEXI TIME APPROVAL COLUMNS
![image](https://cloud.githubusercontent.com/assets/10201846/8450189/e326277c-200a-11e5-9c64-736b149b75ad.png)

**Comment by gigiadamantopoulos** [comment]
No Issues

**Comment by asjr4584** [comment]
@gigiadamantopoulos

All those issues that you have tested and passed please assign them to @lyn2711 . Once the QA Server is ready, @lyn2711 can start testing those issues in the QA Server (her computer).

**Comment by Jinsuke** [comment]
:new: Dashboard UI Update 150716
-
![image](https://cloud.githubusercontent.com/assets/10201846/8716637/bc750870-2bc5-11e5-9fe1-4f969c6f7613.png)

**Note: refer to issue #1 for Dashboard's functionality**

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Passed, test done in 203

**Comment by gigiadamantopoulos** [comment]
Passed in 201
