### ISSUE TITLE
Functionality - Employee Attendance Tracker Viewer

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#15]
**Note: We will PROVIDE Log-in details for agents to view information on the attendance tracker**

**What agents can see and access on the Attendance Tracker Page:**
- Can access PROFILE PAGE which only shows CALENDAR/ATTENDANCE/INSTANCES
- Can see a page wherein Dates with Calendar / Time-in / Time-out is included.
- Users can view acc. minutes of tardiness

**Comment by asjr4584** [comment]
Add History button to the application that will allow the agent to view his/her employee's attendance history through a web browser.

However, he needs to sign in again since application and website have different sessions.

**Comment by asjr4584** [comment]
@alvincrisuycorel what can be done by @chrisperez here?

**Comment by asjr4584** [comment]
Redirection
Page Restriction
Disable Admin Functions

**Comment by chrisperez** [comment]
I forgot to inform you that this is already done together with the **#36 Functionality - User's Hierarchy**

For testing.

**Comment by gigiadamantopoulos** [comment]
Minor UI Issue:

Can we move the texts a little bit to the right? It's too much on the left.

![image](https://cloud.githubusercontent.com/assets/10202106/8781611/aaf494fa-2f42-11e5-83e5-f7d20b43812f.png)

**Comment by Jinsuke** [comment]
:new:  Update
-
- Added **margin-left: 15px** for Agent view.

![image](https://cloud.githubusercontent.com/assets/10201846/8789806/e6c06974-2f78-11e5-8792-27fa2c8ffce3.png)

**Comment by lyn2711** [comment]
Question: If I am an agent, can I edit an Event?  And if I click on Edit, nothing happens.

**Comment by Jinsuke** [comment]
Hi Ms. @lyn2711 ,
   If you're accessing the site as Agent's view, you shouldn't be able edit an event. to sum up the Agent's View:

- Can view Calendar page (Scheduled events approved by TL and Sup. View Only)
- Can view Instances page (Live tracking of Instances, Absences and Late. View Only)
- Change password

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Calendar too wide, alam mo na un @Jinsuke

**Comment by Jinsuke** [comment]
:new: Update
-
- **Fixed Calendar Size for Agent View**
![image](https://cloud.githubusercontent.com/assets/10201846/9323561/5d06da5e-45b4-11e5-96e9-3e4d20d84976.png)

For testing in my local:
http://16.178.42.181/users/profile/102
-

u: jin@gmail.com
p: 123

**Comment by gigiadamantopoulos** [comment]
Passed... ready for merging in 203

**Comment by alvincrisuycorel** [comment]
Merged :smile: 

@gigiadamantopoulos

**Comment by gigiadamantopoulos** [comment]
Passed in 203

**Comment by lyn2711** [comment]
It is smaller but it is positioned at the left side leaving the right side bare.

![image](https://cloud.githubusercontent.com/assets/7370325/9492943/933a1b6a-4c2e-11e5-86ba-8b0f63e0253b.png)

**Comment by asjr4584** [comment]
Deadline: September 2, 2015.

**Comment by Jinsuke** [comment]
Update
-
- Moved Calendar to Center
![image](https://cloud.githubusercontent.com/assets/10201846/9648252/0466110a-5219-11e5-8a53-215202ed9033.png)

**Comment by gigiadamantopoulos** [comment]
passed in 201
