### ISSUE TITLE
UI - Organization Settings

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#16]
Reference from local:
-
![image](https://cloud.githubusercontent.com/assets/10201846/8301542/302a09bc-19c1-11e5-8291-4f6ffd3a175c.png)

**Comment by Jinsuke** [comment]
UI - Organization Settings #16
ORGANIZATION SETTINGS PAGE
-PRIVACY BUTTON is now hidden

**Comment by gigiadamantopoulos** [comment]
Organization ID is not editable.

Organization name is ok.

**Comment by Jinsuke** [comment]
Organization Settings UI
--
- Organization ID is not editable to make it a unique ID.
![image](https://cloud.githubusercontent.com/assets/10201846/8448652/7ffd5732-1ffc-11e5-952c-fc1c048686d6.png)

**Comment by gigiadamantopoulos** [comment]
Organization ID should be auto-generated. Since it's not for the moment, the organization was saved even though the Organization ID was left blank. Since it's not editable, it remained empty.

Please refer to https://github.com/HP-Corel/AttendanceTracker/issues/7

![image](https://cloud.githubusercontent.com/assets/10202106/8459872/ab87bd10-2052-11e5-8587-ed66fbf395e1.png)

**Comment by asjr4584** [comment]
@gigiadamantopoulos is latest comment a UI or Functionality issue? if it's functionality, can you look for the related issue and assign it to @alvincrisuycorel , please? Can you confirm if https://github.com/HP-Corel/AttendanceTracker/issues/16 has no issues in UI? if none, please assign this to @lyn2711

**Comment by gigiadamantopoulos** [comment]
No issue... assigning it to @lyn2711

**Comment by Jinsuke** [comment]
:new: Update
-
- Settings page is now moved to the name of the Organization as a clickable link.
![image](https://cloud.githubusercontent.com/assets/10201846/8819910/286455ec-3083-11e5-9151-61f8247cb362.png)

- "Organization Settings" text under /organization/create is now "CREATE ORGANIZATION"
![image](https://cloud.githubusercontent.com/assets/10201846/8819921/53574a0c-3083-11e5-9537-d4c752c932bd.png)

**Comment by asjr4584** [comment]
@lyn2711 for testing again, please.

**Comment by lyn2711** [comment]
Even if there is a disclaimer at the top of the Delete button, can we still add a message "Are you sure you want to delete "Name of Organization" once "Delete" is clicked?

**Comment by alvincrisuycorel** [comment]
This can be included in the error handling issue #41

**Comment by alvincrisuycorel** [comment]
Done merging. Please check :smile:

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by lyn2711** [comment]
Passed, done in 203

**Comment by gigiadamantopoulos** [comment]
Passed in 201
