### ISSUE TITLE
UI - Reports Page

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#18]
This Page shows all the records and graphs.
-
**FUNCTIONALITY**
* Computation of Absenteeism
* Tardiness and Leaves
* Graphical performance of all agents

**MORE UPDATES Soon once a sample mock has been made.**

**Comment by asjr4584** [comment]
I also would like to see the computation of the following table here:

![image](https://cloud.githubusercontent.com/assets/4827031/8322678/e566a9e8-1a6b-11e5-935e-acb6a76d8b00.png)

**Comment by asjr4584** [comment]
@gigiadamantopoulos can you create a mockup page of the Reportings page where we can export the reports into Excel file. I believe @alvincrisuycorel already shared with you the Excel template the Team Leads are currently using to monitor our attendances. Basically we want to generate the same format within the Reporting Page of The Attendance Tracker Website.

**Comment by gigiadamantopoulos** [comment]
Still working on this one. I'm having a hard time visualizing what reports are needed for this. 

Sir @asjr4584 may I ask what reports are expected to be generated with our system. The Excel Sheet has too much information I can't seem to grasp properly...

**Comment by asjr4584** [comment]
@lyn2711 we need your inputs on this one. Please advise.

**Comment by asjr4584** [comment]
Hi Ma’am Evelyn,

We need your inputs on this one. Please advise.

Regards,
Alfredo “Allan” A. Salvador, Jr.
Team Lead, Customer Solutions Rep V
HP ES Business Process Services

M + 639228901356
E alfredoa.salvadorjr@hp.com<mailto:alfredoa.salvadorjr@hp.com>
Hewlett-Packard Philippines Corporation
4th Floor Two World Square Building
22 Upper McKinley Road, Fort Bonifacio,
Taguig City, Philippines 1634
Philippines

[HP]<http://www.hp.com/>

**Comment by lyn2711** [comment]
Hi @asjr4584 ,

What exact data do you want to be generated? At the bottom of the Excel Sheet, there's a separate table where it computes for the following account-wide:

Present Reps per day
Expected Attendance
Total Authorized Absence per Day
Total Unauthorized Absence per day
Total Absences per Day
Total Planned Leave per Day
Daily Absenteeism Rate - computed as Total Absences per Day / Expected Attendance

Can this be in one single report? And can we have a view to show daily and month-to-date?

There is also data per agent where it will show:
1. Absenteeism - types of absences (count) and MTD Total absences
2. Tardiness - MTD (# of mins late) and Frequency
3. Absenteeism rate - computed as Total Absences / Expected

This can be another report showing daily and month-to-date data.

Please let me know if I miss something.

**Comment by asjr4584** [comment]
Thanks @lyn2711 , @gigiadamantopoulos basically the reports that we need are already in the attendance tracker spreadsheet that @alvincrisuycorel shared with you. Please try to mockup a report page based on @lyn2711 comments above.

**Comment by asjr4584** [comment]
Hi Gigi,

May I follow up your mockups for the Reports page?

Regards,
Alfredo “Allan” A. Salvador, Jr.
Team Lead, Customer Solutions Rep V
HP ES Business Process Services

M + 639228901356
E alfredoa.salvadorjr@hp.com<mailto:alfredoa.salvadorjr@hp.com>
Hewlett-Packard Philippines Corporation
4th Floor Two World Square Building
22 Upper McKinley Road, Fort Bonifacio,
Taguig City, Philippines 1634
Philippines

[HP]<http://www.hp.com/>

**Comment by gigiadamantopoulos** [comment]
Hi Sir @asjr4584 , this is the proposed mock up as discussed with @alvincrisuycorel 

![image](https://cloud.githubusercontent.com/assets/10202106/8560611/3b88ce6a-254c-11e5-80ce-86bca3fedf0c.png)

![image](https://cloud.githubusercontent.com/assets/10202106/8560630/6e99b670-254c-11e5-92db-ef0b1c930641.png)

**Comment by alvincrisuycorel** [comment]
Hi all,

This mock up is base on web master tool in google chrome under crawl errors. 

Functions under reports page
- User can choose which month to be display on the graph. 
- User can choose which year
- User can choose which type of report can be display (e.g Absents, SLs, Emergency leaves, etc)

Graph
- The left side of the graph will be the count of absents or SLs etc. on that month
- Bottom, days in the month.

Reports Page
- Upper part - Graph
- Lower part - History of the graph (similar to web master tool)

**Comment by asjr4584** [comment]
@alvincrisuycorel @gigiadamantopoulos this looks good. What do you think @lyn2711 ?

**Comment by lyn2711** [comment]
Have a question, should VL be considered as an absence?

**Comment by asjr4584** [comment]
Hi Ms. Evs,

Yes VL is considered absent but not counted as an instance.

Can you please suggest a correct arrangement of all the entries in the Add Event Status drop-down list here? http://16.178.42.203/users/profile?userid=2

Group them according to these categories:

Present codes (this could be flexi time, new shift, etc.)
Absence Codes (this could be Holiday, VL, SL, etc.)

**Comment by lyn2711** [comment]
I asked that coz when I looked at the Attendance spreadsheet, at the right side, when it computed for total absences, it only summed up columns AL to AP (A, SL, NCNS, EL and JA).

**Comment by asjr4584** [comment]
Should we also do the same computation in our application?

**Comment by lyn2711** [comment]
It really depends on the requirements of those who will use the reports.  But if we want to show the same thing shown in the sheet, then yes.

**Comment by asjr4584** [comment]
What if we count VL as absence? Will that make any difference in the reporting?

**Comment by lyn2711** [comment]
Yes, especially if we get the absenteeism rate, coz VL will be counted also.

**Comment by asjr4584** [comment]
Okay please discuss that to our developers so they will do the same computation as with the attendance spreadsheet.

Also, please arrange the list of statuses as I mentioned earlier and ask the devs to make the necessary changes.

**Comment by alvincrisuycorel** [comment]
@gigiadamantopoulos Please update the mockup design we have :smile: 

REPORTING PAGE

-	In the line graph. 
o	Change left side of the graph from “5, 10, 15, 20” to “10%, 20%... 100%” – The representation of percentage will be the DAILY ABSENTEEISM RATE in the EXCEL SHEET. 

Please also review the computations given in the EXCEL SHEET. That will serve as our guide

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel ... is this ok?

![image](https://cloud.githubusercontent.com/assets/10202106/8576843/515a2924-25d7-11e5-8734-cd167eb99db2.png)

**Comment by chrisperez** [comment]
For testing once merge with Alvin's Local.

**Comment by chrisperez** [comment]
Added new feature on table. Limited table height and added scroll bars.

**Comment by Jinsuke** [comment]
:new: UI Update 150716
-
![image](https://cloud.githubusercontent.com/assets/10201846/8716693/29326e4e-2bc6-11e5-9884-afac7d4db07f.png)
![image](https://cloud.githubusercontent.com/assets/10201846/8716700/327b2400-2bc6-11e5-8034-5ba3700e014f.png)

:exclamation: **Functionality is on-going.**

**Comment by gigiadamantopoulos** [comment]
Passed... looks great

**Comment by lyn2711** [comment]
Can we have an identifier on what the set of numbers in the screenshot below are?  If I hover my mouse over the points, what are the numbers shown? Is it the number of leaves, etc?

![image](https://cloud.githubusercontent.com/assets/7370325/8801028/153d1a7e-2fea-11e5-99d7-82319140c4a7.png)

**Comment by asjr4584** [comment]
@chrisperez for your comments, please.

**Comment by asjr4584** [comment]
@chrisperez when this going to be ready for testing?

**Comment by chrisperez** [comment]
When you hover on the number, it is the number of person who is on leave or whatever is selected from the report type.

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by gigiadamantopoulos** [comment]
Please add a "Sorry" or a "No Record Found" message if the value is 0

![image](https://cloud.githubusercontent.com/assets/10202106/9054718/e07b7592-3ab6-11e5-8f14-972391aed92f.png)

**Comment by chrisperez** [comment]
Please merge for testing.

**Comment by gigiadamantopoulos** [comment]
Passed. Tested in http://16.178.42.181

**Comment by asjr4584** [comment]
@lyn2711 for testing, please.

**Comment by lyn2711** [comment]
Passed, done on 203

**Comment by gigiadamantopoulos** [comment]
Error in 201:

**Comment by chrisperez** [comment]
Please pull and test in 203

**Comment by lyn2711** [comment]
Can we show in the report details the following:

Expected headcount
Actual headcount
% of Absences

**Comment by asjr4584** [comment]
Deadline: 201 by September 18, 2015

**Comment by chrisperez** [comment]
Adjusted the max_execution_time to -1 in php.ini

This is now loading in 201 though it is still taking too long to load when many people are accessing it.
I tried accessing the reports page around 5 pm yesterday and it loaded fast.

**Comment by asjr4584** [comment]
@chrisperez are we applying pagination to the reports page to make it load much faster? Please advise.

**Comment by asjr4584** [comment]
@chrisperez please include the pagination to the reports page before assigning this back to @gigiadamantopoulos for testing.

**Comment by chrisperez** [comment]
For testing in 201.

**Comment by gigiadamantopoulos** [comment]
Pagination is showing. Passed in 201

**Comment by asjr4584** [comment]
@lyn2711 can you test this today and close if needed, please?

**Comment by chrisperez** [comment]
Please pull latest changes before testing. (Dev, QA and Prod Servers)

**Comment by chrisperez** [comment]
@lyn2711 your comments please.

**Comment by lyn2711** [comment]
Passed, test done in 201

**Comment by asjr4584** [comment]
@chrisperez please fix this ASAP.

**Comment by chrisperez** [comment]
Hi Miss @lyn2711,

Since this issue is regarding UI, maybe we could close this one unless you have additional requirements for me to add.

**Comment by lyn2711** [comment]
None for now. Passed, test done in 201
