### ISSUE TITLE
Functionality - Reports Page

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#19]
This Page shows all the records and graphs.
-
**FUNCTIONALITY**
* Computation of Absenteeism
* Tardiness and Leaves
* Graphical performance of all agents

**MORE UPDATES Soon once a sample mock has been made.**

**Comment by asjr4584** [comment]
@gigiadamantopoulos can you create a mockup page of the Reportings page where we can export the reports into Excel file. I believe @alvincrisuycorel already shared with you the Excel template the Team Leads are currently using to monitor our attendances. Basically we want to generate the same format within the Reporting Page of The Attendance Tracker Website.

**Comment by asjr4584** [comment]
@alvincrisuycorel when do you think we can start this one?

**Comment by Jinsuke** [comment]
:new: UI Update 150716
-
![image](https://cloud.githubusercontent.com/assets/10201846/8716693/29326e4e-2bc6-11e5-9884-afac7d4db07f.png)
![image](https://cloud.githubusercontent.com/assets/10201846/8716700/327b2400-2bc6-11e5-8034-5ba3700e014f.png)

:exclamation: **Functionality is on-going.**

**Comment by Jinsuke** [comment]
Ma’am Evs and I have discussed the Attendance Tracker to Ms. Tara, our new workforce colleague. She will be using the Attendance Tracker (Probably, Supervisor Access) to generate Reports and use it for information tracking of employees.
We’ve noted some of the suggestions and comments from her that might help us in developing the software to make it more efficient.

1.	As per Ms. Tara, she said that there are agents that are “not required” to log-in on the AVAYA CMS during their work shift. This is something that we’re going to clarify to Sir Vince.
2.	AUX 8 (Shortbreak) maximum time should only be for 30 minutes. As from what I understood, AUX 1 would be used for BIO BREAKS (10 minutes). This is to separate computations for BIO Break from Short Breaks.
3.	Groups Page – Suggestion is to display the total number of agents per team on the Group List. As well as attrition of members per fiscal year.
4.	Separate Team Lead positions on the Groups Page. E.g CS – Greggy, CS-Sarih, TS-Robby, TS-Edge, TS-Mark, Dev-Allan. This will be used for generating reports to a specific team.
5.	Individual Groups Page – Suggestion is to be able to extract team member’s data. (member list, etc.)

Ms. Tara will be helping us in the Reports page as she’ll be sending attendance report templates/computations to sir Allan that we can use for the reports generation. These are the some of the things that she has mentioned in the generation of reports:
-	Historical data of instances, tardiness and absences should be saved as a reference (I think these are already included in our current system)
-	Total Adherence Percentage – per team/per agent (Trending Graph)
-	Cumulative tardiness/absences/ncns – per day/month to date/per TL
-	Exporting of reports feature.

**Comment by asjr4584** [comment]
@chrisperez when this going to be ready for testing?

**Comment by chrisperez** [comment]
Please merge. for testing.

@Jinsuke, for the comments from Tara.. please place here those are related only to the reports finctionality. Thanks.

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by lyn2711** [comment]
When a user goes on leave for 2 or more days, can we instead show a date range under the Report Details instead of listing down all the dates? What if it is Maternity Leave which is normally 2-3 months?

**Comment by asjr4584** [comment]
@chrisperez please follow up with Tara the reports template that will be generating from the application.

**Comment by chrisperez** [comment]
Answer the question below..
>When a user goes on leave for 2 or more days, can we instead show a date range under the Report >Details instead of listing down all the dates? What if it is Maternity Leave which is normally 2-3 months?

The view that we have right now is per month only and the records shown are the raw data. I will review the file Tara and Miss Eve gave and will get back to you guys ASAP.

**Comment by asjr4584** [comment]
@lyn2711  for testing in 181.

**Comment by chrisperez** [comment]
Note: Additional colums for short breaks and longbreaks will be implimented next week.

**Comment by alvincrisuycorel** [comment]
Hi Gigi

Kindly test this also :smile:

**Comment by lyn2711** [comment]
Pass, test done in 201

**Comment by asjr4584** [comment]
@Jinsuke @chrisperez re-opening this issue as the Reports page is inaccessible right now:

![image](https://cloud.githubusercontent.com/assets/4827031/9840865/e1a1c17c-5aca-11e5-9484-30f9e24b7849.png)

Please fix this ASAP. This is OVERDUE.

**Comment by chrisperez** [comment]
For testing in 201.

**Comment by gigiadamantopoulos** [comment]
Reports are now accessible in 201.

**Comment by chrisperez** [comment]
Please pull latest changes before testing. (Dev, QA and Prod Servers)

**Comment by asjr4584** [comment]
@lyn2711 for testing, please.

**Comment by lyn2711** [comment]
Passed, test done in 201

**Comment by asjr4584** [comment]
@chrisperez please fix this ASAP.

**Comment by alvincrisuycorel** [comment]
Please test again po :smile:

**Comment by asjr4584** [comment]
@lyn2711 for testing please.

**Comment by lyn2711** [comment]
Passed, test done in 201
