### ISSUE TITLE
Functionality - Access Rights

### ISSUE THREAD

**Issue by alvincrisuycorel** [HP-Corel/AttendanceTracker#20]
Site: http://16.178.42.203/
-
Should not access different URLs when not logged in.

User must redirect to home page when a user access a URL when he/she is not log in

**Sample URLs that you can test.**
http://16.178.42.203/organization/members
http://16.178.42.203/users/profile?userid=2

**Comment by chrisperez** [comment]
Redirects user to /admin/register when not logged in.

**Comment by gigiadamantopoulos** [comment]
Does not redirect to  /admin/register ... instead displays this:

![image](https://cloud.githubusercontent.com/assets/10202106/8416346/b2b7cd36-1ed7-11e5-9ee9-29fafb29928b.png)

**Comment by alvincrisuycorel** [comment]
Hi Gigi, this should not redirect to /admin/register hence it should redirect to 16.178.42.203 which is the home page.

![capture27](https://cloud.githubusercontent.com/assets/7260700/8445983/9ae93ff0-1fd6-11e5-9aa8-a0aa48243617.PNG)

**Comment by gigiadamantopoulos** [comment]
No Issues

**Comment by asjr4584** [comment]
@gigiadamantopoulos 

All those issues that you have tested and passed, I will assign them back to you. Once the QA Server is ready, you need to test those assigned issues to you again.

**Comment by lyn2711** [comment]
Fail. Sample url http://16.178.42.203/users/profile?userid=2 redirects to this page below when not logged in.

![image](https://cloud.githubusercontent.com/assets/7370325/8472783/b993627c-20d6-11e5-897d-d2673ddb1c39.png)

**Comment by asjr4584** [comment]
@lyn2711 for on-going issues, please assign those back to the assigned dev for fixes.

**Comment by asjr4584** [comment]
@lyn2711 also, you may start testing these issues once the QA Server (your computer) has the latest working copy of Attendance Tracker Project. The IP address above is @alvincrisuycorel PC which is currently being tested by Gigi.

**Comment by chrisperez** [comment]
Restricted people from accessing profile page if not logged in.

**Please test all the following pages while not logged in:**
- /organization/overview
- /organization/create
- /profile
- /profile/changepassword
- /organization/dashboard
- /organization/settings
- /organization/members
- /groups
- /groups/view/1
- /roles
- /roles/view/1
- /users/profile?userid=1
- /users/edit?userid=1

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing, please.

**Comment by gigiadamantopoulos** [comment]
All is not accessible and was redirected to the login page, except the last link:
/users/edit?userid=1

![image](https://cloud.githubusercontent.com/assets/10202106/8503797/9fa48590-21f7-11e5-84ed-2b6dcd946361.png)

**Comment by chrisperez** [comment]
Please test again.

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing, please.

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by asjr4584** [comment]
@chrisperez I can access the dashboard even if I'm not login:

http://16.178.42.203/organization/dashboard

can you fix this, please?

**Comment by chrisperez** [comment]
@alvincrisuycorel, please merge my latest update to your local. Let me know if there are issues. If none, please assign to @gigiadamantopoulos to test. Thanks!

**Comment by alvincrisuycorel** [comment]
@gigiadamantopoulos 
Please test :smile:

**Comment by gigiadamantopoulos** [comment]
No issues found. All links are not accessible when logged out

**Comment by lyn2711** [comment]
Pass, all links not accessible when logged out.

**Comment by lyn2711** [comment]
Got an error when accessing /users/profile?userid=1

![image](https://cloud.githubusercontent.com/assets/7370325/9275281/96e2da54-42ce-11e5-8b8a-80e9a40580fc.png)


All other urls not accessible and directs me to the login page

**Comment by chrisperez** [comment]
Please test again.

**Comment by asjr4584** [comment]
@lyn2711  for testing in 181, 203 and 201.

**Comment by lyn2711** [comment]
Passed, test done in 181, 203 and 201
