### ISSUE TITLE
Functionality - Hash Password

### ISSUE THREAD

**Issue by alvincrisuycorel** [HP-Corel/AttendanceTracker#21]
String password will not be seen in database

**Comment by asjr4584** [comment]
Hi @chrisperez is this ready for testing? If so, please assign this now to @gigiadamantopoulos

**Comment by chrisperez** [comment]
**Added hash password function on the following:**
- User First Time Registry
- User Login
- Change Password
- Members > Register Employee

@alvincrisuycorel, Please assign to @gigiadamantopoulos  after merging. Thanks!

**Comment by asjr4584** [comment]
@gigiadamantopoulos this is ready for testing. please test.

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by lyn2711** [comment]
Got an error when changing password

![image](https://cloud.githubusercontent.com/assets/7370325/8841748/5359eb80-3124-11e5-8cb9-38ac922374a6.png)

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by lyn2711** [comment]
Changed password but when I tried logging in, got an error message:

![image](https://cloud.githubusercontent.com/assets/7370325/9275164/c1fc1ff8-42cd-11e5-9c18-ac101d6a50d2.png)

**Comment by Jinsuke** [comment]
Update
-
- This is now fixed on my local. For testing.
http://16.178.42.181/
-

**Comment by gigiadamantopoulos** [comment]
Passed... ready for merging in 203

**Comment by alvincrisuycorel** [comment]
Merged :smile: 

@gigiadamantopoulos

**Comment by gigiadamantopoulos** [comment]
Pass in 203....

**Comment by lyn2711** [comment]
Passed, test done in 181

**Comment by asjr4584** [comment]
@lyn2711 we need to test this again in 201 before assigning this issue back to me. We will not close an issue until we go live.

**Comment by asjr4584** [comment]
by the way @lyn2711 you may close GitHub issue once it was tested and passed in 201. Then assign the issue to me. Thanks!

**Comment by gigiadamantopoulos** [comment]
passed in 201
