### ISSUE TITLE
UI - Responsive Sidebar

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#22]
Sidebar is missing if window is resized smaller.
--
![image](https://cloud.githubusercontent.com/assets/10201846/8404496/173fade4-1e80-11e5-92db-9835aa18d89b.png)

![image](https://cloud.githubusercontent.com/assets/10201846/8404607/df3532ec-1e80-11e5-833a-97cda5eef473.png)

**Comment by asjr4584** [comment]
@Jinsuke what is your progress here?

![image](https://cloud.githubusercontent.com/assets/4827031/8492774/0a26536a-2182-11e5-93dc-41bcefcff875.png)

**Comment by Jinsuke** [comment]
Update
-
Added Sidebar Dropdown for smaller resolutions. (Window Max Width : 767px) :grin: 

**Unclicked**
![image](https://cloud.githubusercontent.com/assets/10201846/8492854/7901ae3c-2183-11e5-9e39-a1d296b6c421.png)

**Clicked**
![image](https://cloud.githubusercontent.com/assets/10201846/8492861/9df672c2-2183-11e5-9acf-b92647c60a0d.png)

**Comment by asjr4584** [comment]
@Jinsuke this looks much better. :+1: 

@gigiadamantopoulos for testing, please.

**Comment by gigiadamantopoulos** [comment]
Hi Kuya @Jinsuke , The dropdown is now working, although the UI is a bit weird with the notification and the Username because it's side by side:
![image](https://cloud.githubusercontent.com/assets/10202106/8503825/1bcd6ccc-21f8-11e5-8380-70b0445707b7.png)

If you expand the username, the notification disappears:
![image](https://cloud.githubusercontent.com/assets/10202106/8503833/4cfa01a2-21f8-11e5-8f7e-d51d78841a02.png)

Can we just add the notification beside the dropdown menu so that the user can see the notification even though the window is small?
![image](https://cloud.githubusercontent.com/assets/10202106/8503844/8728c570-21f8-11e5-8c03-f73f51327cf3.png)

**Comment by Jinsuke** [comment]
Fixed Notification Icon's location when screen is resized.
-

Normal
![image](https://cloud.githubusercontent.com/assets/10201846/8513924/9241c974-23b1-11e5-8dca-94181ec9d570.png)

Resized
![image](https://cloud.githubusercontent.com/assets/10201846/8513936/5513abf2-23b2-11e5-9450-3908da80e02f.png)

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing again, please.

**Comment by gigiadamantopoulos** [comment]
Hi Kuya @Jinsuke , it's ok now, just a minor adjustment:

Can you add more indention on the menu part, the one encircled in red... just so the users can see clearly that the options below are under the Menu title...

![image](https://cloud.githubusercontent.com/assets/10202106/8534061/ae39772a-246b-11e5-9743-62ffe44414d7.png)

**Comment by Jinsuke** [comment]
Update
-
This is already done and will be pushed once the Dashboard #1 has been completed.

![image](https://cloud.githubusercontent.com/assets/10201846/8542954/09070afe-24cc-11e5-8880-c41f39c10a79.png)

![image](https://cloud.githubusercontent.com/assets/10201846/8542965/17b9b0f6-24cc-11e5-9296-718fd0ea4801.png)

**Comment by gigiadamantopoulos** [comment]
Passed!

**Comment by lyn2711** [comment]
![image](https://cloud.githubusercontent.com/assets/7370325/8842057/16f16764-3128-11e5-8b0f-9cb44a363465.png)

**Comment by Jinsuke** [comment]
:new:  Update 150727
-
- **Full Screen**
![image](https://cloud.githubusercontent.com/assets/10201846/8898087/9035b298-3451-11e5-84bc-64d511beb68e.png)

- **Reduced Size with Sidebar**
![image](https://cloud.githubusercontent.com/assets/10201846/8898092/a0bac39c-3451-11e5-8c59-0dcf373e6e84.png)

- **Sidebar compressed**
![image](https://cloud.githubusercontent.com/assets/10201846/8898099/b3a15ae8-3451-11e5-824f-aca50e093377.png)

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Pass, test done on QA server

**Comment by gigiadamantopoulos** [comment]
passed in 201
