### ISSUE TITLE
UI Change - Role Index Page

### ISSUE THREAD

**Issue by chrisperez** [HP-Corel/AttendanceTracker#23]
- Swap Hierarchy Column with Role Column
- Make these two colunms the same in width

**Comment by chrisperez** [comment]
Done with changes

**Comment by gigiadamantopoulos** [comment]
No issues

**Comment by asjr4584** [comment]
@gigiadamantopoulos

All those issues that you have tested and passed please assign them to @lyn2711 . Once the QA Server is ready, @lyn2711 can start testing those issues in the QA Server (her computer).

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Passed, done on 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
