### ISSUE TITLE
Functionality - Create Admin Hierarchy and Manager Role When An Org Was Created

### ISSUE THREAD

**Issue by chrisperez** [HP-Corel/AttendanceTracker#24]
When a new organization was created:
---
- Create a hierarchy named Admin
- Create a role named Manager
- Assign the role to the creator's profile

**Comment by chrisperez** [comment]
Please consolidate and test

**Comment by asjr4584** [comment]
@alvincrisuycorel can you merge this so that @gigiadamantopoulos can do the testing later, please?

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by asjr4584** [comment]
@chrisperez I could not find this GitHub https://github.com/HP-Corel/AttendanceTracker/issues/24 to our timeline sheet. Can you add it there, please?

**Comment by chrisperez** [comment]
@Jinsuke, will add this one. Thanks!

**Comment by gigiadamantopoulos** [comment]
No issues with this one... assigning it to Mam @lyn2711

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Passed, done on 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
