### ISSUE TITLE
Functionality - User Edit and/or Profile Edit

### ISSUE THREAD

**Issue by chrisperez** [HP-Corel/AttendanceTracker#25]
User Edit and/or Profile Edit Pages
---

- Add function that will update the user's details.
- Add Profile Picklist to the Form

**Comment by chrisperez** [comment]
Added functionalities
---
- Update User Record
- Update Role
- Update Group
- Update Shift

**Comment by chrisperez** [comment]
Added Field validations. Please merge and test.

**Comment by asjr4584** [comment]
@alvincrisuycorel can you merge this so that @gigiadamantopoulos can do the testing later, please?

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by asjr4584** [comment]
@chrisperez I could not find this GitHub https://github.com/HP-Corel/AttendanceTracker/issues/25 to our timeline sheet. Can you add it there, please?

**Comment by chrisperez** [comment]
@Jinsuke will add this one. Thanks!

**Comment by gigiadamantopoulos** [comment]
No issues with this. Assigning it to Mam @lyn2711

**Comment by lyn2711** [comment]
Is this correct? When I login and click on Profile, Role and Group is empty as per screenshot below:

![image](https://cloud.githubusercontent.com/assets/7370325/8982706/653a47d2-36f6-11e5-8ef6-57e27ab71353.png)

But when I clicked on Organizations, click on Corel, click Profile, click Edit Profile, Role and Group are filled up:

![image](https://cloud.githubusercontent.com/assets/7370325/8982728/97e95114-36f6-11e5-8137-b1da0437ea24.png)

**Comment by chrisperez** [comment]
Looks good on my local.. can you redo the testing?

**Comment by gigiadamantopoulos** [comment]
For the Manager and Supervisor,

Please disable the Required info for group. They don't have a Team so they should be able to save their profile without this entry

![image](https://cloud.githubusercontent.com/assets/10202106/9054762/3cba63e0-3ab7-11e5-9c1b-e345dc11f343.png)

**Comment by gigiadamantopoulos** [comment]
Nevermind... haha

**Comment by lyn2711** [comment]
I logged in as Allan, clicked on Profile, Role and Group are empty:

![image](https://cloud.githubusercontent.com/assets/7370325/9274922/33e48260-42cc-11e5-9bc7-a062a304f2c1.png)

After that, clicked on Organizations -> Corel -> Profile -> Edit Profile - Role is filled up but Group is blank:

![image](https://cloud.githubusercontent.com/assets/7370325/9274940/606770d6-42cc-11e5-801e-6fbc8bc7832e.png)

**Comment by chrisperez** [comment]
Please try again.

**Comment by asjr4584** [comment]
@lyn2711 for testing 181, 203, 201.

**Comment by lyn2711** [comment]
In 181, Group field in empty, when I logged in and clicked on Profile:

![image](https://cloud.githubusercontent.com/assets/7370325/9495427/136035a4-4c3e-11e5-96af-24fd7a99a04f.png)

Test done in 201 is okay

**Comment by chrisperez** [comment]
Mine is also working. 

@Jinsuke, please pull latest changes to your local.

No Issues here if its still working in 203

**Comment by Jinsuke** [comment]
This is now fixed on my local server. Please test.

![image](https://cloud.githubusercontent.com/assets/10201846/9537822/0be055c4-4d70-11e5-966b-44bc7c6141a5.png)

**Comment by lyn2711** [comment]
Disable Profile button upon logging in and when user has not selected an organization yet.

**Comment by asjr4584** [comment]
Deadline: September 2, 2015.

**Comment by Jinsuke** [comment]
Update
-
Done in my local pc. For Testing on local.
http://16.178.42.181/
-
**All Passwords are: 123**
- **Admin Account:** jin@gmail.com

- **Supervisor Account:** alvincris.uy@hp.com

- **TL Account:**
  - Dev Team: alfredoa.salvadorjr@hp.com
  - Team Robby: mark@gmail.com

- **Agent Account:**
  - Dev Team:
    - christopher.perez@hp.com
  - Team Robby:
    - pogs@gmail.com

**Comment by lyn2711** [comment]
Pass, test done in 181

**Comment by Jinsuke** [comment]
Transferred to 203 for testing.

**Comment by lyn2711** [comment]
Pass, test done in 203

**Comment by Jinsuke** [comment]
For testing on Prod.

**Comment by gigiadamantopoulos** [comment]
passed in 201

**Comment by gigiadamantopoulos** [comment]
Issue in Server: http://c9t16755.itcs.hpecorp.net/users/change/87

When editing and saving the profile, it displays this error.
![image](https://cloud.githubusercontent.com/assets/10202106/10420396/8cb97af4-70c5-11e5-8d26-7691ffd25abc.png)

**Comment by alvincrisuycorel** [comment]
Hi Gigi, @gigiadamantopoulos 

Kindly test when editing profile when using an account for manager, supervisor, team lead and agent.

**Comment by gigiadamantopoulos** [comment]
Email / Employee ID
manager@123.com     -12345
supervisor@123.com   -124
tl1@123.com                -125
tl2@123.com                -126
agent1@123.com         -127
agent2@123.com         -128

All Passed...
