### ISSUE TITLE
UI - Individual Role Page

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#26]
Page where to assign Roles to a user.
--
- ADD/REMOVE user
- EDIT button to direct to User Profile Edit page.

![image](https://cloud.githubusercontent.com/assets/10201846/8449808/286a91fa-2007-11e5-9ee8-02dc5fcc1316.png)

Site: http://16.178.42.203/roles/view/1
--

**Comment by gigiadamantopoulos** [comment]
No Issues

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Passed, done on 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
