### ISSUE TITLE
Functionality - Change Password

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#28]
On /profile/changepassword
--
- Password change works on the first run. You can even check it change on the database, but after changing the password, and you've tried changing again, you'll get a wrong password input from the new password.

Steps to see the issue:
- Change password from old to new
- Get a password changed successfully
- Change password again by using the new password as the old password
- Get a wrong password input
- Old original password still works on the site, New password is already changed in the database

Screenshot
--
![image](https://cloud.githubusercontent.com/assets/10201846/8450024/4c6041de-2009-11e5-8c7a-6f26fd97b767.png)

Site: http://16.178.42.203/profile/changepassword
--

**Comment by Jinsuke** [comment]
This is now working and has been pushed to dev. :smirk: 
--
![image](https://cloud.githubusercontent.com/assets/10201846/8468054/35087372-2099-11e5-9f08-603a7cec5e1d.png)

Thanks kuya @chrisperez !
Site: http://16.178.42.203/profile/changepassword
--

**Comment by asjr4584** [comment]
Hi Jin,

Can you also add another field here where a user must re-type his/her new password for confirmation?


![image](https://cloud.githubusercontent.com/assets/4827031/8469417/1f6cf5c4-20ad-11e5-9603-644515ded18c.png)

**Comment by asjr4584** [comment]
Hi Jin,

Can you also add another field here where a user must re-type his/her new password for confirmation?
[cid:image001.png@01D0B4B9.A57593C0]

**Comment by Jinsuke** [comment]
Re-type New Password has been added on the Attendance Tracker.
--

![image](https://cloud.githubusercontent.com/assets/10201846/8470485/81fad68c-20be-11e5-884d-e01ed321b028.png)

Site: http://16.178.42.203/profile/changepassword
--

**Comment by gigiadamantopoulos** [comment]
Hi kuya @Jinsuke ,

This should be in asterisk form right since we're dealing with passwords?

![image](https://cloud.githubusercontent.com/assets/10202106/8482759/37ce2ebe-211e-11e5-9c39-f5ac10fdbc20.png)

**Comment by Jinsuke** [comment]
Done! :)
--
![image](https://cloud.githubusercontent.com/assets/10201846/8489979/77a4b888-2154-11e5-868d-b2d0af3d373c.png)

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing again, please.

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by lyn2711** [comment]
Refer to issue #21

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Passed, done on 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
