### ISSUE TITLE
UI- Individual Profile Page (Calendar Tab)

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#29]
Features
--
- This is where Admins can plot Agent events like VL, SL, New Schedule, etc.
- Events should be shown on the calendar according to their assigned dates.
- If NEW SHIFT Status is selected, there should be another field to select Shifts.

Screenshot
--
![image](https://cloud.githubusercontent.com/assets/10201846/8450346/b1b160a6-200c-11e5-85fb-885c51821069.png)
![image](https://cloud.githubusercontent.com/assets/10201846/8450349/b6ff30ec-200c-11e5-95e0-a4c1bda6c109.png)

Site: http://16.178.42.203/users/profile?userid=1
--

**Comment by gigiadamantopoulos** [comment]
No Issues

**Comment by Jinsuke** [comment]
Make Calendar Responsive
--

**Comment by Jinsuke** [comment]
Changes
-
- Fixed Calendar's responsiveness when browser size is moved.
- Fixed ADD EVENT and Calendar's windows
![image](https://cloud.githubusercontent.com/assets/10201846/8490876/d7498e9a-2162-11e5-9529-7965d0873c5a.png)

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing, please.

**Comment by Jinsuke** [comment]
Updates
-
- Changed Tab Order [Calendar, Attendance, Instances]
- Calendar now appears (without clicking Today button)

![image](https://cloud.githubusercontent.com/assets/10201846/8498040/f69be390-21b4-11e5-9226-832b036b4569.png)

**Comment by gigiadamantopoulos** [comment]
Hi Kuya @Jinsuke , 

The tab names are ok, but the content stayed the same sequence as before:
![image](https://cloud.githubusercontent.com/assets/10202106/8503879/11de96e0-21f9-11e5-9433-ae9749bd3ae3.png)

![image](https://cloud.githubusercontent.com/assets/10202106/8503880/18d78592-21f9-11e5-92d0-d1f192a50179.png)

**Comment by Jinsuke** [comment]
Hi @gigiadamantopoulos ,

Thanks for pointing it out. :sweat_smile:  I've tried checking on it on my local pc and the tab contents seems to be just fine. Maybe it wasn't included in Alvin's PC. I'll let him know about this later.

**Comment by asjr4584** [comment]
@alvincrisuycorel please check this out.

**Comment by alvincrisuycorel** [comment]
This is now working :smile:

**Comment by gigiadamantopoulos** [comment]
Passed!

**Comment by Jinsuke** [comment]
:new: UPDATE 150715
-
- **EVENTS** toggle should have EDIT and REMOVE BUTTON
 - EDIT BUTTON when clicked should have a pop-up for editing event schedule.
 - REMOVE BUTTON will delete event schedule.

**Comment by Jinsuke** [comment]
Update
-
- Added Edit button with popup on Event Toggle
![image](https://cloud.githubusercontent.com/assets/10201846/8714297/d4f6052c-2ba5-11e5-9f9f-dfec65771111.png)

- Edit Event Pop Up
![image](https://cloud.githubusercontent.com/assets/10201846/8714301/e78a8b36-2ba5-11e5-9ab0-8d363527d171.png)

**Comment by gigiadamantopoulos** [comment]
Hi kuya @Jinsuke , 

Pop-up not showing.

Minor edit: Can we make all the title uniform? Like make it all in Caps?

![image](https://cloud.githubusercontent.com/assets/10202106/8781329/e6c3109e-2f40-11e5-87bd-a306c3490e20.png)

**Comment by Jinsuke** [comment]
:new: Update
-
- Changed text to ALLCAPS.

![image](https://cloud.githubusercontent.com/assets/10201846/8789633/008654d8-2f77-11e5-81c7-030b874e08fd.png)

**Comment by Jinsuke** [comment]
:new: Update
-
- **CHANGED ADD EVENT FORM UI AND REMOVED TOGGLE**
![image](https://cloud.githubusercontent.com/assets/10201846/8816651/6891a2e0-305c-11e5-82f7-3859b0c7b176.png)
- **CHANGED EDIT EVENT MODAL**
![image](https://cloud.githubusercontent.com/assets/10201846/8816654/7ccfab26-305c-11e5-8714-393f3575acc1.png)

**Comment by lyn2711** [comment]
Can we make Start Date and End Date's positioning the same?

![image](https://cloud.githubusercontent.com/assets/7370325/8842504/949321ee-312d-11e5-8f31-97cfe290af03.png)

**Comment by Jinsuke** [comment]
Update 150724
-
- This is now fixed. For testing.
![image](https://cloud.githubusercontent.com/assets/10201846/8868861/b7071b3a-320f-11e5-8f12-f329e72e0eef.png)

**Comment by lyn2711** [comment]
Can we differentiate the events (leaves, holidays) in the Calendar by color so it will be easier to distinguish one from the other?

Example:
VL - green
SL - yellow
NCNS - red
etc.

**Comment by alvincrisuycorel** [comment]
Hi Ma'am Evs,

Could you list all the colors of the statuses? 

PLANNED ABSENCE
Off - Rest Day                                           
P - Present      
VL - Vacation Leave (Planned Leave)        
T- Training
ML - Maternity Leave                                   
S - Separated
LOA - Leave of Absence                             
SLOA - Suspended
PL - Paternity Leave

UNPLANNED ABSENCE  
A -  Unauthorize Absence                    
UT - Undertime
NCNS - No Call No Show                         
SL - Authorized Absence                     
JA - Job Abandonment 
1SL - 1st Half Authorized Absence       
EL - Emergency Leave
2SL - 2nd Half Authorized Absence

Or it would be easier po if we only have 2 colors for both Planned and Unplanned absences :smile:

**Comment by gigiadamantopoulos** [comment]
Passed...

Color coding to be done in the future

**Comment by Jinsuke** [comment]
:new: Task
-
Show the agent's name in the Group Calendar to identify the filed event.
![image](https://cloud.githubusercontent.com/assets/10201846/9079138/86ad7f10-3b79-11e5-8697-ae479d6ea4e0.png)

**Comment by Jinsuke** [comment]
:new: Fix Update
-
Added Name table.
![image](https://cloud.githubusercontent.com/assets/10201846/9079932/b0034004-3b81-11e5-9757-281062457deb.png)

**Comment by gigiadamantopoulos** [comment]
Passed. Tested using http://16.178.42.181/

**Comment by alvincrisuycorel** [comment]
Done

**Comment by gigiadamantopoulos** [comment]
PAssed!

**Comment by Jinsuke** [comment]
Update
-
- Edited Calendar Event Table Font Sizes
![image](https://cloud.githubusercontent.com/assets/10201846/9127189/98b233f6-3ce9-11e5-986a-303a0a411ce2.png)

**Comment by lyn2711** [comment]
Passed, done on 203

**Comment by gigiadamantopoulos** [comment]
passed in 201

**Comment by gigiadamantopoulos** [comment]
Issue on Server: http://c9t16755.itcs.hpecorp.net/users/profile/3

UI: 
![image](https://cloud.githubusercontent.com/assets/10202106/10387409/c2c9abde-6e93-11e5-9b46-b64ddde94785.png)

**Comment by alvincrisuycorel** [comment]
Hi Gigi, @gigiadamantopoulos 

Kindly check in dev server :smile:

**Comment by gigiadamantopoulos** [comment]
Passed:

![image](https://cloud.githubusercontent.com/assets/10202106/10444525/5f36f1f8-719a-11e5-98c3-5abc4e3f97b6.png)
