### ISSUE TITLE
UI- Individual Profile Page (InstancesTab)

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#31]
Site: http://16.178.42.203/users/profile?userid=1
--
Features
--
- Page to let Admins / Regular user to see their Lates/Instances/Sick Leaves.
- Admin access has the right to reset tardiness count on the Instances toggle.

Screenshot
--
![image](https://cloud.githubusercontent.com/assets/10201846/8450445/897ca9f0-200d-11e5-851b-5ef6a00fd8ed.png)

**Comment by gigiadamantopoulos** [comment]
No Issues

**Comment by asjr4584** [comment]
Thanks Gigi,

I would like further changes to the Absenteeism table:

(1)	Replace disable with excuse and the function should be similar to flexi schedule.
(2)	Reset Instances check boxes will act, as "Select ALL" so if reset is both approved by TL & Sup, the checkboxes from the entries will be marked check too.
(3)	Per row check boxes are for individual excuse; reset checkboxes will reset all but the records are still there.

 
![sdfad](https://cloud.githubusercontent.com/assets/4827031/8589813/ca861676-264c-11e5-9c69-a2801cd25843.png)


What do you think?

**Comment by gigiadamantopoulos** [comment]
Hi Sir @asjr4584, here's the mock-up

![image](https://cloud.githubusercontent.com/assets/10202106/8606855/48ed3a34-26c1-11e5-9130-1d5131e1ccdb.png)

**Comment by alvincrisuycorel** [comment]
@gigiadamantopoulos kindly access and check this UI on the site?

**Comment by Jinsuke** [comment]
Update
-
- Slightly working functionalities [Login/Shortbreak/Longbreak/Status/Late in Minutes counting]

**To Follow:**
- Fix table information per day and per month 
- Fix Total Minutes of Late/No. of instances and Rest Tardiness Button
- Fix Absenteeism table

**NOTE: TABS HAS BEEN CHANGED. CALENDAR, ATTENDANCE AND INSTANCES TABS ARE NOW SEPARATE PAGES**

Screenshot
-
![image](https://cloud.githubusercontent.com/assets/10201846/8668704/7c29e32a-2a40-11e5-9c78-2e390a867e91.png)
![image](https://cloud.githubusercontent.com/assets/10201846/8668714/9400bcf8-2a40-11e5-8d46-eda08c2a048b.png)

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel ,

Just to clarify, the table will expand downwards whenever there are instances right? What happens to the "Totals" and "Overalls" ???

![image](https://cloud.githubusercontent.com/assets/10202106/8781191/31b5f8d8-2f40-11e5-905d-9e33b8d3f084.png)

**Comment by lyn2711** [comment]
Suggestion:

![image](https://cloud.githubusercontent.com/assets/7370325/8843666/0ca9977a-313e-11e5-9314-ed437ca39e67.png)

**Comment by Jinsuke** [comment]
:new: Update 150727
-
- Changed text for overall and total instances/late record.
- Added responsive tables instead of div
![image](https://cloud.githubusercontent.com/assets/10201846/8896907/d075effe-343c-11e5-853a-40a3866f1d10.png)

**Comment by lyn2711** [comment]
Can we put in the center the Monthly and Overall table?

![image](https://cloud.githubusercontent.com/assets/7370325/8982445/ecc94642-36f3-11e5-9ff8-0689a30cad8a.png)

**Comment by alvincrisuycorel** [comment]
Done. Please check

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by lyn2711** [comment]
Passed, done on 203

**Comment by lyn2711** [comment]
Can we change "Total # of Late" to "Total mins late".  And I think it should be shown in minutes even if it is over 60 minutes.

![image](https://cloud.githubusercontent.com/assets/7370325/9274326/60642a2a-42c7-11e5-902f-9d736b50694e.png)

**Comment by Jinsuke** [comment]
Update
-
- Changed Table title to TOTAL MINS LATE
![image](https://cloud.githubusercontent.com/assets/10201846/9296520/1eebb5c6-44c1-11e5-8a0b-71553b159a23.png)

As discussed, time will still be the same (hours:minutes:seconds). :)

For testing on my local: 
http://16.178.42.181/users/instances/35002194
-

**Comment by gigiadamantopoulos** [comment]
Passed in 181

**Comment by alvincrisuycorel** [comment]
Done :smile:

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing in 203, 201

**Comment by gigiadamantopoulos** [comment]
Passed in both 203 and 201

**Comment by lyn2711** [comment]
Passed, test done in 201

**Comment by gigiadamantopoulos** [comment]
Passed...
