### ISSUE TITLE
Functionality - Notification icon (beside the User Profile tab)

### ISSUE THREAD

**Issue by asjr4584** [HP-Corel/AttendanceTracker#33]
Admins should receive a notification when:
-

-  An agent incurred an instance
-  An agent reached 3 instances or accumulated 60 minutes of lates
-  An agent is on vacation, sick, etc.
-  A Supervisor approves/rejects a flexi
-  An agent forgot to logout after his/her shift (notification 4 hours after his/her shift)

Is it possible to receive an email notification of the above conditions?

**Comment by alvincrisuycorel** [comment]
Hi sir I think it will be possible.

From who's email will we gonna use from sending the email messages?

**Comment by asjr4584** [comment]
Hi Alvin,

Can we use a dummy email (from Gmail) for now to test this functionality?

Also, email notifications should only be received by TL/Supervisor of that Agent.

Can that be done?

**Comment by alvincrisuycorel** [comment]
I'm not sure yet sir if email functionality will work because the system only works locally not on a live server. Though we can give it a try if emailing system will work on a local network only.

References for local server
http://roshanbh.com.np/2007/12/sending-e-mail-from-localhost-in-php-in-windows-environment.html

cakephp implementation
http://book.cakephp.org/2.0/en/core-utility-libraries/email.html

**Comment by asjr4584** [comment]
Thanks Alvin,

To Everyone,

I also would like to get a notification when an agent forgot to logout his/her attendance tracker app; although this is not counted as an instance, a notification will be sent to his/her TL/Sup 4-hours after his/her shift.

**Comment by asjr4584** [comment]
Hi @alvincrisuycorel and @gigiadamantopoulos ,

Do you still remember the Pre-Made Music from Corel?

When a user goes to Pre-Made Music Google Site and enter his chosen music to the Pre-Made Music Google Form, an email notification shall be sent to the user’s email address that includes the download link of that music. The download links are stored in the Google Excel Log Sheet where you can also see the details of the user who request the download.

I remember Alvin created a script for that Google Excel Log Sheet so that download links will be sent to the user’s email address.

I would like the same idea to be implemented to our Attendance Tracker Project. Let us use Google Email, Google Forms, to send notifications to Team Leads, Supervisors, and Managers if a certain criteria is met. 

@alvincrisuycorel please check how can this be done. Do we need to embed Google Forms on our Attendance Tracker Website? Attached is the script you created for that form.

@gigiadamantopoulos please do additional mockups for the notification process when we use Google forms.

**Comment by chrisperez** [comment]
Function of the Notification Bell is - Done

However, the comeplete functionality of the notification has not been started. Such Functions includes:
- Creating a notification message. 
- Assigning the notification to the right person.
- Sending email allert to the key person.

**Comment by alvincrisuycorel** [comment]
- An agent incurred an instance 
- An agent reached 3 instances or accumulated 60 minutes of lates
- An agent is on vacation, sick, etc.
- A Supervisor approves/rejects a flexi :white_check_mark: 
- An agent forgot to logout after his/her shift (notification 4 hours after his/her shift)

**Comment by alvincrisuycorel** [comment]
Questions:
- An agent incurred an instance
Who are the admins? Manager, Supervisor, and the Team Lead? or Just the Manager

- An agent is on vacation, sick, etc.
Will the notification applies when the TL or Sup added a vacation, sick etc to the agent?
Example: After adding an event for the agent a notification will be send to the TL sup manager.
or
Will the notification applies if an agent is VL, SL, etc on that current day.
Example: today is 7/24/2015 and an agent is currently on VL. The system will send a notification to the TL that an agent is VL today

- An agent forgot to logout after his/her shift (notification 4 hours after his/her shift)
This would be hard because our system does not apply a bot that would detect and track a user if he/she is not logged in and it's already 4 hrs after he/she logged out.

**Comment by alvincrisuycorel** [comment]
- An agent incurred an instance :white_check_mark: 
- An agent reached 3 instances or accumulated 60 minutes of lates
- An agent is on vacation, sick, etc. :white_check_mark: 
- A Supervisor approves/rejects a flexi :white_check_mark:

**Comment by alvincrisuycorel** [comment]
- An agent reached 3 instances or accumulated 60 minutes of lates

I think that, this is a large feature that could automate the notifications. Similar to (BOT)
- An agent forgot to logout after his/her shift (notification 4 hours after his/her shift)

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel is it possible that the instances occurred by the agents will send a notification to their TLs only? The Supervisor will only receive notifications regarding approvals.

This is to prevent the clutter on the notification page of both the TLs and Supervisors.

**Comment by alvincrisuycorel** [comment]
Okie :smile:

**Comment by alvincrisuycorel** [comment]
Done. Please test :smile:

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by lyn2711** [comment]
Passed, test done on 203

**Comment by gigiadamantopoulos** [comment]
passed in 201

**Comment by asjr4584** [comment]
OVERDUE

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel ,

As experienced by Sir @asjr4584 , there is no notification sent to the TL when we occurred an instance , also when the TL clicked on the Reset Tardiness Count, the Supervisor did not receive any notification as well and the checkbox is not clickable...

Can you please double check?

**Comment by alvincrisuycorel** [comment]
Hi Gigi I will investigate.

**Comment by alvincrisuycorel** [comment]
https://github.com/HP-Corel/AttendanceTracker/issues

**Comment by asjr4584** [comment]
Hi Team,

Can you we prioritize this, please?

**Comment by alvincrisuycorel** [comment]
Hi sir ok po.

Deadline September 14, 2015

**Comment by alvincrisuycorel** [comment]
Added
- Notification for Supervisor when TL check the checkbox in instance page
- Notification for TL when Supervisor check the checkbox in instance page
- Notification for TL when Supervisor click the button of reset tardy count
- Notification for TL when Supervisor click the button of reset instance
- Notification for TL when an Agent occur an instance when a TL or a Supervisor access the instance page of that Agent have an instance
- No need to refresh instance page to show instances of the Agent

Hi Gigi kindly check the ff. if these are correct in 203

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel .... there are still some issues as discussed.

**Comment by alvincrisuycorel** [comment]
Hi Gigi could you test it again?

@gigiadamantopoulos

**Comment by gigiadamantopoulos** [comment]
Passed! Please merge to 201

**Comment by alvincrisuycorel** [comment]
Hi kuya Jerome :smile: 

Kindly merge po in 201 :smile:

**Comment by Jinsuke** [comment]
Thank you kuya @alvincrisuycorel  :grimacing: 

For testing on 201.

**Comment by gigiadamantopoulos** [comment]
This is passed in 201

**Comment by gigiadamantopoulos** [comment]
Hi Kuya @Jinsuke , as reported by sir @asjr4584 :

Hi Gigi,
I noticed that you would not see the new notifications unless you open the instance tab of a user:
Is there a workaround on this to make it automatic?

![image](https://cloud.githubusercontent.com/assets/10202106/10091870/04ee81c8-6373-11e5-983a-27adcb0ff126.png)

http://16.178.42.201/profile/notifications

**Comment by Jinsuke** [comment]
Hi @gigiadamantopoulos  and Sir @asjr4584 ,

As discussed with @alvincrisuycorel , it seems that this is the most feasible way to notify supervisors/team leads about their Agent's instances. We would need a *'bot'* if we need to check who occurred an instance in real time.

**Comment by asjr4584** [comment]
@Jinsuke can we run a 'bot' on our local computer?

**Comment by asjr4584** [comment]
@Jinsuke why I am still getting a lot of instances with the same date in the notification?

![2015-10-02_0922](https://cloud.githubusercontent.com/assets/4827031/10237666/2eb27946-68e7-11e5-8a21-7b7fd8c0b6cf.png)

**Comment by asjr4584** [comment]
@Jinsuke we have now identified that every time you refresh the user profile page, the TL keeps getting notification of the same instances. Please fix this ASAP.

**Comment by Jinsuke** [comment]
Update
-
- For testing on local.

**Comment by lyn2711** [comment]
Passed, test done in 181

**Comment by alvincrisuycorel** [comment]
Merged in 203

**Comment by lyn2711** [comment]
Passed, test done in 203

**Comment by Jinsuke** [comment]
For testing on Production 201 http://16.178.42.201/
-

**Comment by lyn2711** [comment]
Passed, test done in 201

**Comment by gigiadamantopoulos** [comment]
Old notification is disappeared on the page as reported by Peter Chan.

**Comment by Jinsuke** [comment]
The reason why the old notification disappeared is probably because we have cleaned the database and filed their approved leaves. Peter Chan might be looking for his past notifications which what happened was, we plotted the leaves ourselves.
