### ISSUE TITLE
Software - Login/AUX Functionalities

### ISSUE THREAD

**Issue by alvincrisuycorel** [HP-Corel/AttendanceTracker#35]
Software UI Update
--
Logout not yet functioning :smile: 

![image](https://cloud.githubusercontent.com/assets/10201846/8449896/fc1b1164-2007-11e5-952a-e8846de4613e.png)

**Comment by alvincrisuycorel** [comment]
Logout not yet functioning :smile:

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing, please.

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel , I can't seem to test the software. It keeps on crashing when I open it. I'm using the latest version that you sent in my email.

https://cloud.githubusercontent.com/assets/10202106/8503778/2ddee77a-21f7-11e5-81e4-57ee0825b265.png

**Comment by asjr4584** [comment]
@gigiadamantopoulos, please test the latest software sent by @alvincrisuycorel.

**Comment by gigiadamantopoulos** [comment]
This is passed :D

**Comment by asjr4584** [comment]
@alvincrisuycorel i'm assigning this to you because I think the "View Records" button is still not working. Please transfer this issue back to @gigiadamantopoulos if the "View Records" is fully working.

**Comment by alvincrisuycorel** [comment]
@gigiadamantopoulos  ,

Hi Gigi, could you test it again if the "View Records" button will redirect you to the site's home page login?

**Comment by asjr4584** [comment]
@lyn2711 i'm assigning this to you for testing today since @gigiadamantopoulos is on vacation.

**Comment by asjr4584** [comment]
@lyn2711 please disregard my message. @gigiadamantopoulos for testing tonight, please.

**Comment by gigiadamantopoulos** [comment]
View Records button is working, when clicked, it directed me to the homepage, but though I am logged in, it still shows the login page.

![image](https://cloud.githubusercontent.com/assets/10202106/8601684/316b9e08-26a0-11e5-860d-1b637c756beb.png)

**Comment by gigiadamantopoulos** [comment]
After 5 mins, the software crashed again...

![image](https://cloud.githubusercontent.com/assets/10202106/8601783/f54daa14-26a0-11e5-8a25-16f0bb7e08e4.png)

**Comment by alvincrisuycorel** [comment]
Hi Gigi, @gigiadamantopoulos 

I will confirm this :smiley: thank you for reporting :+1:

**Comment by alvincrisuycorel** [comment]
Hi Gigi please try again :smile:

**Comment by gigiadamantopoulos** [comment]
It's ok now @alvincrisuycorel . thanks!

**Comment by lyn2711** [comment]
Program crashes

![image](https://cloud.githubusercontent.com/assets/7370325/8801589/65b8376e-2fee-11e5-9318-a06e2f6b17af.png)

**Comment by alvincrisuycorel** [comment]
Hi Ma'am Evs,

@lyn2711

When did this happened?

When clicking a certain button like logout and different auxes or it just stop working?

**Comment by lyn2711** [comment]
When I click View Records, it directs me to the login page. It should be directed to the profile page

**Comment by alvincrisuycorel** [comment]
Fixed. Kindly test po again :smile:

**Comment by lyn2711** [comment]
Same thing happens. When I click on View Records, it still directs me to the login page.

**Comment by alvincrisuycorel** [comment]
Hi Ma'am Evs, @lyn2711 

If you are logged in already in the website. You must redirected to the user profile when you click the "View Record" in the software.

If you are not logged in in the website. You must be redirected to the login page when you click the "View Record" in the software.

Are these still not happening?

**Comment by gigiadamantopoulos** [comment]
Clicking the logout button results to crashing

**Comment by alvincrisuycorel** [comment]
Hi Gigi please check if the message is fine when changing the status of the user :smile:

**Comment by alvincrisuycorel** [comment]
- Added Software application can only have one instance

**Comment by alvincrisuycorel** [comment]
Hi Gigi

@gigiadamantopoulos 

Please change the popup alert messages on the software :smile: :pouch:

**Comment by gigiadamantopoulos** [comment]
- When you logout then you log in, the buttons should be disabled to avoid the crash
- Alert the user when you first log in for Aux 7.

**Comment by alvincrisuycorel** [comment]
Hi Gigi

@gigiadamantopoulos 

Please test po again :smile:

**Comment by gigiadamantopoulos** [comment]
Passed!

**Comment by lyn2711** [comment]
Pass, test done in http://16.178.42.201/
