### ISSUE TITLE
Functionality - Create Organization (Organization ID)

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#37]
Hi All,

As discussed in https://github.com/HP-Corel/AttendanceTracker/issues/7

Organization ID should be automated and cannot be edited when creating an organization.

![image](https://cloud.githubusercontent.com/assets/10202106/8528197/266d62e2-2444-11e5-9a59-d7a938e70dd4.png)

As what @alvincrisuycorel mentioned: The organization id will be used in the future. I put it there so that the user can choose his/her organization id not generated by the system (this is to make the admin aware of the id he/she created for that organization). It will be more difficult if the system will create an ID base on the organization name.

Though this feature is still not used in our system but in some case if the system goes larger the organization id will be use for addressing urls. Example usage

The admin/manager can switch different organization by just typing

(future - multiple organization can be viewed at once in different tab)
http://16.178.42.203/corel/dashboard
http://16.178.42.203/guthyrenker/dashboard

http://16.178.42.203/organization/dashboard (current implementation - 1 organization only can be viewed)

**Comment by asjr4584** [comment]
@alvincrisuycorel can you add this to our timeline spreadsheet, please?

**Comment by asjr4584** [comment]
@gigiadamantopoulos please move this to Milestone 4 in the timeline spreadsheet.

**Comment by chrisperez** [comment]
Done. Please pull latest changes to your local @Jinsuke and pass to @gigiadamantopoulos for testing.

**Comment by Jinsuke** [comment]
Done pulling on my local. For testing!

http://16.178.42.181/
-

**Comment by gigiadamantopoulos** [comment]
Passed in 181 and 201.

**Comment by asjr4584** [comment]
@lyn2711 for testing in 201.

**Comment by lyn2711** [comment]
Passed, test done in 201
