### ISSUE TITLE
UI - Notification Page

### ISSUE THREAD

**Issue by chrisperez** [HP-Corel/AttendanceTracker#38]
Create a page where users can view their notification details.

**Comment by chrisperez** [comment]
@Jinsuke, Please add this to our spreadsheet. Thanks.

**Comment by chrisperez** [comment]
New page has been created. Please add this to our slides also @gigiadamantopoulos.

**Comment by Jinsuke** [comment]
Done adding on Spreadsheet. :smile:

**Comment by lyn2711** [comment]
Suggestion:  Replace the word "Subject" with "Messages"

![image](https://cloud.githubusercontent.com/assets/7370325/8845206/56441fca-314f-11e5-93d5-7699d08738d2.png)

**Comment by chrisperez** [comment]
Done with changes.

![image](https://cloud.githubusercontent.com/assets/4833394/8896927/41b8d258-343d-11e5-8371-4bb5156b3680.png)

**Comment by lyn2711** [comment]
![image](https://cloud.githubusercontent.com/assets/7370325/8980225/945ad1cc-36e1-11e5-83d8-7522372b4666.png)

**Comment by chrisperez** [comment]
How about this instead to be uniform with other pages?

![image](https://cloud.githubusercontent.com/assets/4833394/9000186/205717dc-3776-11e5-9a53-2bbd0e9674dc.png)

**Comment by gigiadamantopoulos** [comment]
Notification contains codes...

![image](https://cloud.githubusercontent.com/assets/10202106/9054977/ea503dee-3ab8-11e5-8a43-a0d04d55a88d.png)

**Comment by gigiadamantopoulos** [comment]
Passed. Tested in http://16.178.42.203/

**Comment by lyn2711** [comment]
Pass, test done in  http://16.178.42.201/

**Comment by Jinsuke** [comment]
Added Table Color
-
![image](https://cloud.githubusercontent.com/assets/10201846/11716019/c7f4338a-9f81-11e5-8617-76844a596e1d.png)
