### ISSUE TITLE
UI - Member's Page

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#4]
This page shows the list of all the members in the Organization (including those who doesn't have a TEAM).
-
USER INTERFACE
*SEARCH member
*ADD member button
*REMOVE member button

FUNCTIONALITIES
*SEARCH member
*ADD members
*REMOVE members

Reference Mockup
![image](https://cloud.githubusercontent.com/assets/10201846/8295926/5e1c24bc-197c-11e5-9de2-2df8daef9e04.png)

**Comment by Jinsuke** [comment]
*Add MEMBERS AND CALENDAR TAB
*MEMBERS tab still has the same output
*Add CALENDAR Function that will show users who are on leave (Refer to Outlook's Calendar)

**Comment by Jinsuke** [comment]
UI - Member's Page #4
MEMBER PAGE
-working links for NAMES and EDIT button

**Comment by gigiadamantopoulos** [comment]
No issues

**Comment by Jinsuke** [comment]
150630 UI UPDATE

MEMBERS TAB
![image](https://cloud.githubusercontent.com/assets/10201846/8421872/a45ae85c-1f06-11e5-955a-d876c9a75486.png)

REGISTER EMPLOYEE TAB
![image](https://cloud.githubusercontent.com/assets/10201846/8421874/b2b9578a-1f06-11e5-8ec1-7a4cd7cfe912.png)

**Comment by gigiadamantopoulos** [comment]
Hi,

Question, can we add a dropdown list of the Group and Role when you are registering an employee? So that when you register a new employee, you don't have to go to the group or role tab just to add them...

![image](https://cloud.githubusercontent.com/assets/10202106/8462563/5a94c7c6-2067-11e5-9b06-caade9fcfcb2.png)

**Comment by asjr4584** [comment]
@Jinsuke can you comment on this, please?

**Comment by Jinsuke** [comment]
Added Group, Role and Shift Dropdown selections when registering an employee
-
![image](https://cloud.githubusercontent.com/assets/10201846/8490910/a32feef0-2163-11e5-91e3-0686fdc0dbbe.png)

Functionality is still ongoing. Please refer to Issue #5 for functionality.

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing please.

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by Jinsuke** [comment]
:new: UPDATE 150715
-
- **EVENTS** toggle should have EDIT and REMOVE BUTTON
 - EDIT BUTTON when clicked should have a pop-up for editing event schedule.
 - REMOVE BUTTON will delete event schedule.

**Comment by Jinsuke** [comment]
Update
-
**MEMBER'S PAGE**
![image](https://cloud.githubusercontent.com/assets/10201846/8712401/724bc0fe-2b8e-11e5-893d-dea715a260fd.png)
**CALENDAR**
![image](https://cloud.githubusercontent.com/assets/10201846/8712406/7f75beec-2b8e-11e5-92d1-65d17033af7b.png)
**REGISTER EMPLOYEE**
![image](https://cloud.githubusercontent.com/assets/10201846/8712415/8b5ebb00-2b8e-11e5-9f47-04ea322f3983.png)

***FUNCTIONALITY NOT YET WORKING FOR CALENDAR***

**Comment by gigiadamantopoulos** [comment]
Passed!

**Comment by Jinsuke** [comment]
:new: Update
-
- **CALENDAR** has now been moved to Sidebar.

![image](https://cloud.githubusercontent.com/assets/10201846/8789584/866a7b48-2f76-11e5-843d-22faffec13c5.png)

**Comment by lyn2711** [comment]
Admin Account - Calendar:  Suggestion

Since the event added here are holidays, can we rename "Add Event" to "Add Holidays" then remove "Status"?

Then can we change "Status" to "Holidays" and then in the dropdown list, we can show there all the holidays.

**Comment by Jinsuke** [comment]
Hi Ms. @lyn2711 ,

Thank you for your suggestion but as of the moment, there would be no need to make specific holidays for selections as discussed. :relieved:

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Pass, test done on QA server

**Comment by Jinsuke** [comment]
:new: Update
-
Member's page is now on Ascending Order.

![image](https://cloud.githubusercontent.com/assets/10201846/9265821/341672c2-426b-11e5-9f43-0400075cf827.png)

**Comment by lyn2711** [comment]
Pass, test done in 203

**Comment by gigiadamantopoulos** [comment]
Passed in 201
