### ISSUE TITLE
Functionality - 24/7 Work Schedule

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#40]
TASK
-
- This feature should be implemented on the **users/profile** page (Calendar Event filing).
- When selecting **Off (Rest Day)** in the **ADD EVENT** selection, a new field should appear where Admins can select specific days for an individual agent to set as their Rest Day for the week.
 - This will be in Check boxes and two (2) check boxes can only be selected.
- Total of work per week is 40 hours.

**NOTE: As discussed, it won't be that long till we may be required to go to work even on weekends. We need to include a function where Admins can file/schedule their Agents Rest Days manually and allow them to select specific days for an individual agent.**

**Comment by asjr4584** [comment]
@gigiadamantopoulos please create a UI mockup of this feature.

**Comment by gigiadamantopoulos** [comment]
Hi Sir,

As discussed earlier, the Off-Day setting will be included in the "Members Profile Page".

![image](https://cloud.githubusercontent.com/assets/10202106/8856411/4a9cb0f8-319d-11e5-8404-505a29624c4b.png)

Once 2 days are selected, 

![image](https://cloud.githubusercontent.com/assets/10202106/8856693/f6033e7a-319e-11e5-8978-d3d63fbac33d.png)

it should be reflected to the calendar of the member.

![image](https://cloud.githubusercontent.com/assets/10202106/8856801/ac11c13c-319f-11e5-9cae-51d2b2c47589.png)

**Comment by Jinsuke** [comment]
Update 150729
-
![image](https://cloud.githubusercontent.com/assets/10201846/8951030/aa4dbc10-35fb-11e5-997b-5ab946bca7d2.png)

**Functions not yet done**

**Comment by alvincrisuycorel** [comment]
Hi @gigiadamantopoulos 

Could you test this? :smile:

**Comment by gigiadamantopoulos** [comment]
Passed... although in the edit profile, please disable the checkbox if two days are already chosen... @alvincrisuycorel 

![image](https://cloud.githubusercontent.com/assets/10202106/9054996/1c695324-3ab9-11e5-9c19-778186939ee5.png)

**Comment by lyn2711** [comment]
Other boxes still not disabled when selecting 2 days:

![image](https://cloud.githubusercontent.com/assets/7370325/9111792/fe4b93a0-3c7c-11e5-8008-e6a8f5d51115.png)

**Comment by Jinsuke** [comment]
:new: Update
-
http://16.178.42.181/organization/register
-
- Fixed checkbox disable button when selecting more than two off-days.
![image](https://cloud.githubusercontent.com/assets/10201846/9129429/34cc3794-3d0a-11e5-93ae-bd0486e3c4b3.png)

**Comment by asjr4584** [comment]
Deadline: August 7, 2015.

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by lyn2711** [comment]
Pass, test done in 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
