### ISSUE TITLE
Functionality - Error Handling

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#41]
Task
-
- Ensure that all pages has their own Error Handling messages, correct URL redirections.
- Task is to test all pages for all possible errors.
 - e.g. Wrong Password, Buttons that are not yet working, correct URL redirections
- If something has been found that needs error handling, please indicate the exact issue, possible error message and solution.

**Comment by alvincrisuycorel** [comment]
- admin/register (will use AJAX for checking details)
-- Employee id checker
-- Email checker
-- Password strength checker
-- Password Confirm checker

**Comment by asjr4584** [comment]
@Jinsuke I'm assigning this to you.

Please add this github issue to Milestone 2 and Timeline Spreadsheet: https://my.sharepoint.hp.com/my/asiapacific_salvadoa/Documents/Attendance%20Tracker%20Application%20Project/Attendance%20and%20Time%20Tracker%20Project%20Timeline.xlsx?Web=1

**Comment by lyn2711** [comment]
Notification: (Suggestion)
If there are no notifications, when you hover over the icon, a message "No new notifications" will appear.

**Comment by Jinsuke** [comment]
![image](https://cloud.githubusercontent.com/assets/10201846/8925985/9a58ae72-353e-11e5-824c-7a9e73920575.png)

**Comment by Jinsuke** [comment]
Update 150729
-
![image](https://cloud.githubusercontent.com/assets/10201846/8950960/e13a5b6c-35fa-11e5-85c9-76a975bb0d91.png)

**Comment by Jinsuke** [comment]
From @gigiadamantopoulos 
Here’s what I found:

- When I remove my own account in the list of members, this message occurs:
![image](https://cloud.githubusercontent.com/assets/10201846/8978141/ef450dec-36d1-11e5-846a-d9125e1af7f6.png)

  - Then I clicked the back button, my account was removed as well as the organization:
![image](https://cloud.githubusercontent.com/assets/10201846/8978145/00fc086a-36d2-11e5-99d9-508902241144.png)

  - **Solution:** This option should not be possible. If it is, a pop up message should appear when you remove yourself that the account and the organization will also be deleted. Something that would look like this:
![image](https://cloud.githubusercontent.com/assets/10201846/8978151/11835292-36d2-11e5-9d47-d5f3c5e2282e.png)

- When you delete an organization and tried to re-create it with the same ID and Organization name, it will display this:
![image](https://cloud.githubusercontent.com/assets/10201846/8978178/3b6de446-36d2-11e5-8978-28561595c133.png)

  - **Solution:** It should display an error message that the OrgID or Org name is already existing. Or better yet, once you delete an organization, it should accept the new OrgID and OrgName even if it was previously deleted.
![image](https://cloud.githubusercontent.com/assets/10201846/8978187/4a47985e-36d2-11e5-8caf-9547fc694e9a.png)

**Comment by Jinsuke** [comment]
Hi @gigiadamantopoulos ,

I have included your suggestions for the error handling in this issue. Some of the suggestions that you have sent will be discussed tomorrow if it would be approved or not. For now, can you help and check the whole system for more error checking? :grin: Congratulations! :confetti_ball:

**Comment by Jinsuke** [comment]
:new: Update
-
![image](https://cloud.githubusercontent.com/assets/10201846/9031902/b60f6582-39eb-11e5-8a93-b3fd2d65f48d.png)

**Comment by Jinsuke** [comment]
:new Update
-
![image](https://cloud.githubusercontent.com/assets/10201846/9051681/5a7aef3e-3a90-11e5-8999-568f1b915b3b.png)

**Comment by asjr4584** [comment]
@Jinsuke when is this going to be ready for testing?

**Comment by Jinsuke** [comment]
:new: Update
-
![image](https://cloud.githubusercontent.com/assets/10201846/9076101/b20e9a0a-3b50-11e5-95e1-1b5ee1c2feed.png)

**Comment by Jinsuke** [comment]
:new: Update
-
![image](https://cloud.githubusercontent.com/assets/10201846/9101895/1db4d304-3c1f-11e5-9263-d5961811696c.png)

**Comment by asjr4584** [comment]
Deadline: Wednesday, August 12, 2015.

**Comment by Jinsuke** [comment]
:new: Update 150810
-
![image](https://cloud.githubusercontent.com/assets/10201846/9161632/bd7c382a-3f74-11e5-91ff-e2bcdad7c70a.png)

**Comment by Jinsuke** [comment]
:new:  Update
-
![image](https://cloud.githubusercontent.com/assets/10201846/9188793/07c58eba-4013-11e5-869f-0f70bd39593d.png)

**Comment by Jinsuke** [comment]
:new: Update
-
![image](https://cloud.githubusercontent.com/assets/10201846/9213856/b46395ac-40c9-11e5-9dd9-564b22a6f3d3.png)

**Comment by Jinsuke** [comment]
:new: Update 150814
-
![image](https://cloud.githubusercontent.com/assets/10201846/9264675/89f8bd22-425b-11e5-982b-fc13380d0e04.png)

**ALL DONE! Thank you** @alvincrisuycorel :grin:

**Comment by alvincrisuycorel** [comment]
Hi @gigiadamantopoulos 

Please test :smile:

**Comment by lyn2711** [comment]
![image](https://cloud.githubusercontent.com/assets/7370325/9272799/8fbe4b16-42b8-11e5-8513-4ba481ccc280.png)


Tried to register a new member and got myself an error.  Plus, the 1st break, lunch and 2nd break are all 12AM

![image](https://cloud.githubusercontent.com/assets/7370325/9272873/3cfee2d6-42b9-11e5-9879-10aad3849772.png)

**Comment by lyn2711** [comment]
Can we change the confirmation messages for delete/remove/setting button from "Confirm" to for example:

![image](https://cloud.githubusercontent.com/assets/7370325/9273021/a1151848-42ba-11e5-9e7c-db5df10ded51.png)

![image](https://cloud.githubusercontent.com/assets/7370325/9273032/c15eecd2-42ba-11e5-8846-e5211dd6bf1b.png)

![image](https://cloud.githubusercontent.com/assets/7370325/9273047/f1880826-42ba-11e5-98ff-226a27d2dce1.png)

**Comment by chrisperez** [comment]
Assigning this to @Jinsuke :+1:

**Comment by Jinsuke** [comment]
Done in Local. For Testing.
http://16.178.42.181/organization/dashboard
-

**Comment by gigiadamantopoulos** [comment]
Passed.... tested in 181.. please merge @alvincrisuycorel  :D

**Comment by alvincrisuycorel** [comment]
merged in 203 :smiley:

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing in 203, 201

**Comment by gigiadamantopoulos** [comment]
Passed in 203

**Comment by lyn2711** [comment]
![image](https://cloud.githubusercontent.com/assets/7370325/9493018/2e36d234-4c2f-11e5-86f2-d2eed0c2b245.png)

"Confirm" was not changed to "Remove Member"

**Comment by lyn2711** [comment]
Passed in 201
