### ISSUE TITLE
Notification for removed employees

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#42]
"When you add the same person on another role, then that person will be included in that role. However, his name from the previous role will be removed."

Can we add like a notification or a pop-up alert that the person was removed to another role?

Please refer to https://github.com/HP-Corel/AttendanceTracker/issues/12#issuecomment-121156368

**Comment by asjr4584** [comment]
@gigiadamantopoulos can you add this to the timeline spreadsheet, please? Under Milestone 3.

https://my.sharepoint.hp.com/my/asiapacific_salvadoa/Documents/Attendance%20Tracker%20Application%20Project/Attendance%20and%20Time%20Tracker%20Project%20Timeline.xlsx?Web=1

**Comment by gigiadamantopoulos** [comment]
Done!

**Comment by lyn2711** [comment]
Is this done already, coz when I tested, there was no notification or pop up alert.

**Comment by asjr4584** [comment]
Deadline: Friday, August 14, 2015.
