### ISSUE TITLE
Error Handling: Transferring roles 

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#44]
Issue: 

I tried adding a Team Lead account into an Agent role. While it did delete the account from the Team Lead list, it did not show a confirmation message that it was deleted.

Solution:
![image](https://cloud.githubusercontent.com/assets/10202106/9030992/813febf0-39dd-11e5-9998-fa6359e36f52.png)

Sir @asjr4584 's comment:
- only applicable to Manager and Supervisor

**Comment by asjr4584** [comment]
@gigiadamantopoulos please add this to the timeline spreadsheet, under Milestone 4.

**Comment by alvincrisuycorel** [comment]
Hi Gigi

@gigiadamantopoulos 

Is it possible that the 2nd image above that the TLs will receive become a notification? It has a similar function to notification.

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel , yes, i think that's more correct

**Comment by asjr4584** [comment]
Deadline: Monday, August 10, 2015.

**Comment by Jinsuke** [comment]
Update
-
As discussed, this will not be implemented as changing user roles are already working. Transferred issue to sir @asjr4584 .
