### ISSUE TITLE
Extract Data for Reports

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#48]
Task
-
Suggestion is to be able to extract team member’s data. (member list, etc.) to export data into Excel format.

**Comment by asjr4584** [comment]
@gigiadamantopoulos is this already added to our timeline spreadsheet?

**Comment by gigiadamantopoulos** [comment]
Added

**Comment by asjr4584** [comment]
Deadline: 201 by September 30, 2015

**Comment by chrisperez** [comment]
Please pull and test to dev, QA and Prod Servers.

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing please.

**Comment by lyn2711** [comment]
Passed, test done in 203

**Comment by asjr4584** [comment]
@gigiadamantopoulos please test in 201.

**Comment by Jinsuke** [comment]
Testing Production 201
-
- Results: OK :+1: 

![image](https://cloud.githubusercontent.com/assets/10201846/10210351/6147af72-6818-11e5-87ee-dee4238a8d55.png)
