### ISSUE TITLE
Functionality - Member's Page

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#5]
Site: http://16.178.42.203/organization/members
-
This page shows the list of all the members in the Organization (including those who doesn't have a TEAM).

**USER INTERFACE**
- SEARCH member
- ADD member button
- REMOVE member button

**FUNCTIONALITIES**
- SEARCH member
- ADD members
- REMOVE members

Reference Mockup
-
![image](https://cloud.githubusercontent.com/assets/10201846/8295926/5e1c24bc-197c-11e5-9de2-2df8daef9e04.png)

**Comment by Jinsuke** [comment]
*Add MEMBERS AND CALENDAR TAB
*MEMBERS tab still has the same output
*Add CALENDAR Function that will show users who are on leave (Refer to Outlook's Calendar)

**Comment by gigiadamantopoulos** [comment]
No issues. User lands on the profile page when a member is clicked.

**Comment by Jinsuke** [comment]
150630 UI UPDATE

MEMBERS TAB
![image](https://cloud.githubusercontent.com/assets/10201846/8421872/a45ae85c-1f06-11e5-955a-d876c9a75486.png)

REGISTER EMPLOYEE TAB
![image](https://cloud.githubusercontent.com/assets/10201846/8421874/b2b9578a-1f06-11e5-8ec1-7a4cd7cfe912.png)

**Comment by gigiadamantopoulos** [comment]
No Issues

**Comment by Jinsuke** [comment]
Site: http://16.178.42.203/organization/members
--
Added Role and Group dropdown selection on Register Employee Tab.
--

![image](https://cloud.githubusercontent.com/assets/10201846/8468219/df33beea-209b-11e5-8a37-57ba1d718fda.png)

**Comment by asjr4584** [comment]
Hi Jin,

Can I register an employee if there is no group available yet?

Is the Role field and Group field mandatory?

**Comment by Jinsuke** [comment]
**Hi Sir @asjr4584 ,**
The Role and Group field is not mandatory. Admins can still create User accounts without inputting fields for Role and Group. :sweat_smile:

**Comment by asjr4584** [comment]
Thanks @Jinsuke , in the future, let's add a help button or notification button just beside those fields so that admins are aware that they should create groups or roles first before adding members.

looping in @chrisperez , @alvincrisuycorel @gigiadamantopoulos and @lyn2711

**Comment by alvincrisuycorel** [comment]
Additionals:

*Add search bar for finding employees/user that will be added in the list of org members 
- search function can find existing users that does not have an organization (employees can not have 2 or more orgs)

**Comment by chrisperez** [comment]
Added Search Member to Member Page to look for existing members from the database that are not yet in an organization.

To test, do the following:
- Create a new organization
- Create/register a new user/member
- Delete the new org created
- Select an existing org
- Go to members and search for the new user that you have just created from the deleted org.

**Comment by gigiadamantopoulos** [comment]
Passed!

**Comment by Jinsuke** [comment]
:new: UPDATE 150715
-
- **EVENTS** toggle should have EDIT and REMOVE BUTTON
 - EDIT BUTTON when clicked should have a pop-up for editing event schedule.
 - REMOVE BUTTON will delete event schedule.

**Comment by Jinsuke** [comment]
:new: Update
-
- **CALENDAR** has now been moved to Sidebar.

![image](https://cloud.githubusercontent.com/assets/10201846/8789584/866a7b48-2f76-11e5-843d-22faffec13c5.png)

**Comment by Jinsuke** [comment]
:new: Update
-
- Global Calendar event filing is now working
![image](https://cloud.githubusercontent.com/assets/10201846/8868716/fb7007fc-320d-11e5-8cf1-bad3e25d5a7c.png)

**Comment by lyn2711** [comment]
Tried to create a new org, register a member and I got an error as per screenshot below:

![image](https://cloud.githubusercontent.com/assets/7370325/8875380/658fcb94-324b-11e5-9154-534114526ea3.png)

**Comment by Jinsuke** [comment]
Hi @lyn2711 ,

I believe that the reason is because of the duplicate Employee IDs,  you might have registered using an employee ID who is already included. In Alvin's PC, I have registeredall the agents, supervisor, team lead's accounts along with their employee IDs. So that maybe the reason why this happened. :grin: Thank you!!!

**Comment by lyn2711** [comment]
Okay, tried to create an org again, register a member and made sure that it is not a duplicate employee ID and I got an Internal Error.

![image](https://cloud.githubusercontent.com/assets/7370325/8957749/0dc9394a-3633-11e5-9f71-0e364a543f29.png)

**Comment by alvincrisuycorel** [comment]
Please check

**Comment by gigiadamantopoulos** [comment]
Passed.

Minor rev, @alvincrisuycorel 
Please disable the checkbox if 2 checkbox are already selected
![image](https://cloud.githubusercontent.com/assets/10202106/9054581/81f4576a-3ab5-11e5-834f-269dadf59e64.png)

**Comment by lyn2711** [comment]
Pass, test done on QA server

**Comment by Jinsuke** [comment]
Update
-
- Fix OffDays checkbox. Please test.
![image](https://cloud.githubusercontent.com/assets/10201846/9188896/25f10954-4014-11e5-8062-91c602ec5309.png)

**Comment by gigiadamantopoulos** [comment]
Passed. Tested in 181

**Comment by alvincrisuycorel** [comment]
Done Merge. Please test in 203

**Comment by gigiadamantopoulos** [comment]
Hi Kuya @Jinsuke , as discussed, the Admin should still edit the day-off even after his/her account has been created. 

Thanks!

**Comment by Jinsuke** [comment]
Update
-
**DONE!** For testing in Local:
http://16.178.42.181/users/edit?userid=1
-
![image](https://cloud.githubusercontent.com/assets/10201846/9215928/20467d92-40e4-11e5-9bda-fee326d4f223.png)

**Comment by gigiadamantopoulos** [comment]
Passed! Please pull for 201. Thanks

**Comment by alvincrisuycorel** [comment]
Ma'am @lyn2711 will test in 203. Before pulling in 201

**Comment by lyn2711** [comment]
Pass, test done in 203.

**Comment by gigiadamantopoulos** [comment]
Passed in 201
