### ISSUE TITLE
Total number of Teams

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#50]
Hi,

As suggested by Tara, on the red box, please add a total number of the employees under that team.

![image](https://cloud.githubusercontent.com/assets/10202106/9076866/3c628d0c-3b5a-11e5-9dbd-22291ab1f5c2.png)

**Comment by chrisperez** [comment]
Added members count to Group List. Please merge for testing.

![image](https://cloud.githubusercontent.com/assets/4833394/9077658/47d2fdf8-3b63-11e5-969d-75343cf6f592.png)

**Comment by gigiadamantopoulos** [comment]
Hi Sir @chrisperez 

The number of members are still 1.

![image](https://cloud.githubusercontent.com/assets/10202106/9105462/a3f8320a-3c4a-11e5-9539-c13e18f79779.png)

![image](https://cloud.githubusercontent.com/assets/10202106/9105464/a958fe32-3c4a-11e5-8ab9-2929523ae959.png)

**Comment by chrisperez** [comment]
Fix Group members count. Please merge for testing.

**Comment by alvincrisuycorel** [comment]
Done merging :smile:

**Comment by chrisperez** [comment]
For testing @gigiadamantopoulos

**Comment by gigiadamantopoulos** [comment]
Passed in 203...

**Comment by chrisperez** [comment]
Hi @lyn2711,

For testing in 201...

**Comment by alvincrisuycorel** [comment]
Hi Gigi

Please notify me if this is ready to merge in 201

**Comment by gigiadamantopoulos** [comment]
Passed in 201...
![image](https://cloud.githubusercontent.com/assets/10202106/9160618/7171d6ca-3f6e-11e5-94f4-1daecd71279c.png)

**Comment by lyn2711** [comment]
Test done in 203.

Change "Admins" to "Admin" And is it correct that there is no Remove button beside Admin?

![image](https://cloud.githubusercontent.com/assets/7370325/9273749/110d710c-42c2-11e5-8c5a-25e3d17dd725.png)

**Comment by chrisperez** [comment]
Miss @lyn2711,

Please see comments below.

 - Change "Admins" to "Admin" - `this is for Issue #51`
 - And is it correct that there is no Remove button beside Admin? - `Admin is a super group and must not be deleted`

**Comment by lyn2711** [comment]
Passed, done in 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
