### ISSUE TITLE
Auto Create Admin Group

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#51]
Hi,

Is it possible that when you first register a manager account, an ADMIN group will be auto created and the Manager will be added there?

![image](https://cloud.githubusercontent.com/assets/10202106/9077221/2235a668-3b5e-11e5-9878-933eac2e533e.png)

Thanks!!!

**Comment by chrisperez** [comment]
Done. Please merge for testing.

![image](https://cloud.githubusercontent.com/assets/4833394/9077679/98a22a74-3b63-11e5-921f-33598da13f3d.png)

**Comment by alvincrisuycorel** [comment]
Already merge.

@gigiadamantopoulos

**Comment by gigiadamantopoulos** [comment]
Hi Sir @chrisperez , can we change the group to Admin and not Admins?

This is passed. Thanks!

**Comment by chrisperez** [comment]
Changed "Admins" to "Adimn". Please Merge for testing.

**Comment by alvincrisuycorel** [comment]
Done merging on my local server

**Comment by gigiadamantopoulos** [comment]
Passed!

**Comment by lyn2711** [comment]
Under Groups, it still shows "Admins". Test done in 203

**Comment by chrisperez** [comment]
Please merge to 203 for testing.

**Comment by gigiadamantopoulos** [comment]
PASS! in 181

**Comment by chrisperez** [comment]
Please merge in 203 for testing.

**Comment by gigiadamantopoulos** [comment]
Passed.. tested in 201

**Comment by asjr4584** [comment]
@lyn2711 for testing in 201.

**Comment by lyn2711** [comment]
Passed, test done in 201
