### ISSUE TITLE
Wrong logic - Aux 7

### ISSUE THREAD

**Issue by alvincrisuycorel** [HP-Corel/AttendanceTracker#52]
Wrong output Summing up all AUX 7 (On Desk)

This occurrence happens when the shift of the user is between two days
Ex. 7PM - 4AM from Aug 5 to Aug 6 (2 Days)

**Comment by asjr4584** [comment]
Deadline: Wednesday, August 12, 2015.

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel , 

Agents did not log out, but they didn't log in either

![image](https://cloud.githubusercontent.com/assets/10202106/9157524/af88f3de-3f33-11e5-9c87-817073c927f3.png)

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel ,

Another issue, agent logs out, but the status says Not  yet logged out

![image](https://cloud.githubusercontent.com/assets/10202106/9157641/75827066-3f38-11e5-9c9f-5806843b7fa6.png)

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel ,

Another issue... employee logs in at 12mn, logs out at 9pm.... is this possible?

![image](https://cloud.githubusercontent.com/assets/10202106/9157658/0898f94c-3f39-11e5-8ca6-72ba7844418b.png)

**Comment by alvincrisuycorel** [comment]
Please test. Done merging :smile:

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel , here are some issues I found:

1. Shift displayed in the dashboard is not the same as what is displayed in the software
![image](https://cloud.githubusercontent.com/assets/10202106/9215380/670e7d7c-40dc-11e5-8fec-2925c0463e1d.png)
![image](https://cloud.githubusercontent.com/assets/10202106/9215381/71bb160e-40dc-11e5-93a4-fa600550959a.png)

2. In the dashboard, the shift of employee 24 was logged in, eventhough it was employee 25 was logged in. I assumed the shift of employee 24 was displayed as the shift of employee 25.
![image](https://cloud.githubusercontent.com/assets/10202106/9215410/d6b71210-40dc-11e5-8b58-c2a760d0c4a8.png)

3. I changed one shift of an employee, then I went back to the dashboard, and it displayed this error:
![image](https://cloud.githubusercontent.com/assets/10202106/9215434/31aeb59c-40dd-11e5-93b0-48787085c5c9.png)

**Comment by alvincrisuycorel** [comment]
Hi @gigiadamantopoulos could you test it again?

**Comment by lyn2711** [comment]
Changed Francisco, Christine's shift to 1:30-10:30 PM and shift in Dashboard did not change:

![image](https://cloud.githubusercontent.com/assets/7370325/9272672/6ff0d020-42b7-11e5-8925-c9ea3cf72ce0.png)

![image](https://cloud.githubusercontent.com/assets/7370325/9272685/8855f974-42b7-11e5-9e47-ae32bac5bdb3.png)

**Comment by asjr4584** [comment]
@lyn2711 for testing in 201.

**Comment by lyn2711** [comment]
Passed, test done in 201
