### ISSUE TITLE
Wrong Notification Message

### ISSUE THREAD

**Issue by alvincrisuycorel** [HP-Corel/AttendanceTracker#53]
Wrong Notification received by Team Leads when an instance is created. 

Only Scenario
- When a user add an event for the agent for
A, SL, NCNS, EL, JA
this must send a notification

- When a user visit the profile->instance page of an employee. If and only if that employee has an instance

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel , it works fine as what you mentioned above.

**Comment by lyn2711** [comment]
Pass, test done on 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
