### ISSUE TITLE
Functionality - User's Hierarchy Edit Settings

### ISSUE THREAD

**Issue by chrisperez** [HP-Corel/AttendanceTracker#58]
Create a page where you can edit the Access Settings of the created Hierarchy.

![image](https://cloud.githubusercontent.com/assets/4833394/9213837/5e839826-40c9-11e5-8a94-4d55e9eb5477.png)

**Comment by chrisperez** [comment]
Done with UI and Functionality. Ready for testing @gigiadamantopoulos.

**Comment by gigiadamantopoulos** [comment]
PASS!!! Please pull for 201.

**Comment by alvincrisuycorel** [comment]
Ma'am @lyn2711 will test in 203. Before pulling in 201

**Comment by lyn2711** [comment]
Pass, test done in 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
