### ISSUE TITLE
Add Password Field in the Software login

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#59]
Hi @alvincrisuycorel ,

As discussed, please add a password field in the software login. The password that they will use is the same password that they will use to login in the web.

**Comment by alvincrisuycorel** [comment]
Hi Gigi,

Please test :smile:

**Comment by gigiadamantopoulos** [comment]
Passed. Please pull for 201.

**Comment by alvincrisuycorel** [comment]
Ma'am @lyn2711 will test in 203. Before pulling in 201

**Comment by lyn2711** [comment]
Pass, test done in 203

**Comment by alvincrisuycorel** [comment]
Test in 201 po :smile:

**Comment by lyn2711** [comment]
Pass, test done in 203

**Comment by lyn2711** [comment]
Pass, test done in 201
