### ISSUE TITLE
UI - Create Organization page

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#6]
User Interface for Creating Organizations. 
-
**USER INTERFACE**
- Organization ID
- Organization Name
- CREATE button
- CANCEL button

**FUNCTIONALITY**
- CREATE
- CANCEL

**Reference Mockup**
![image](https://cloud.githubusercontent.com/assets/10201846/8296037/d77aa54e-197d-11e5-8d38-bc6ac8de3b89.png)

**Comment by alvincrisuycorel** [comment]
The image above is for creating the groups. Though creating organization UI is now working :+1:

**Comment by asjr4584** [comment]
Hi Alvin, is this for testing in your local?

**Comment by gigiadamantopoulos** [comment]
No Issues

**Comment by Jinsuke** [comment]
150630 UI UPDATE

![image](https://cloud.githubusercontent.com/assets/10201846/8421861/7f4789c6-1f06-11e5-8cfa-75fe5b9a9a02.png)

**Comment by gigiadamantopoulos** [comment]
No Issues

**Comment by asjr4584** [comment]
@gigiadamantopoulos

All those issues that you have tested and passed please assign them to @lyn2711 . Once the QA Server is ready, @lyn2711 can start testing those issues in the QA Server (her computer).

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Pass, test done on QA server

**Comment by gigiadamantopoulos** [comment]
Passed in 201
