### ISSUE TITLE
UI: Alert Window

### ISSUE THREAD

**Issue by lyn2711** [HP-Corel/AttendanceTracker#61]
Suggestion:
When alert shows up, user cannot go to other pages/windows unless he clicks on OK on the alert window

OR

We can do away with the alert window, and just show the overbreak in red color and blinking (if possible).  User cannot also go to other windows, unless user clicks on "On Desk"

**Comment by asjr4584** [comment]
Change the background color of the form. or background color of label.

**Comment by asjr4584** [comment]
@alvincrisuycorel please assist @Jinsuke

**Comment by Jinsuke** [comment]
As Discussed with @alvincrisuycorel ,
- Time duration text color is now changed to Red.
- It will be difficult to implement the red button when agent is on overbreak.

- Changes will be seen on the next export of the Tracker software.

**Comment by Jinsuke** [comment]
Update
-
- Fix DONE by @chrisperez 
![image](https://cloud.githubusercontent.com/assets/10201846/9652290/8cf7e916-524c-11e5-8bb4-2b709a778593.png)

**Comment by gigiadamantopoulos** [comment]
Passed on 203

**Comment by gigiadamantopoulos** [comment]
passed in 201
