### ISSUE TITLE
UI: Include Login time

### ISSUE THREAD

**Issue by lyn2711** [HP-Corel/AttendanceTracker#62]
Suggestion:
Please include login time in the Attendance tracker, after Shift.

**Comment by asjr4584** [comment]
![image](https://cloud.githubusercontent.com/assets/4827031/9376897/9810cb36-4745-11e5-9b7c-9b847ce3cd7e.png)

Deadline: August 24, 2015

**Comment by asjr4584** [comment]
Deadline: September 15, 2015.

**Comment by chrisperez** [comment]
For testing in 201

**Comment by lyn2711** [comment]
Passed, test done in 201
