### ISSUE TITLE
Deleted employee remains inside a team

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#63]
Hi, 

Found this issue in 201. When I delete an employee in the organization, that employee still remains on the group/teams list.

**Comment by asjr4584** [comment]
Deadline: August 24, 2015

**Comment by chrisperez** [comment]
Please merge for testing. Thanks!

**Comment by Jinsuke** [comment]
Done Merging. For Testing on my local. 
http://16.178.42.181/organization/members
-

**Comment by gigiadamantopoulos** [comment]
Testes and passed in 203.. ready for merging in 201

**Comment by lyn2711** [comment]
Passed, test done in 181

**Comment by asjr4584** [comment]
@Jinsuke please merge this in 201 and then assign to @lyn2711 for testing.

**Comment by asjr4584** [comment]
@lyn2711 please test this today in 201.

**Comment by Jinsuke** [comment]
Pushed in 201. Please test.
http://16.178.42.201/
-

**Comment by lyn2711** [comment]
Passed, test done in 201
