### ISSUE TITLE
Filtering of Dashboard entries

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#65]
As discussed, please add a filter on the entries of the dashboard.

**Comment by asjr4584** [comment]
Deadline: September 15, 2015.

**Comment by Jinsuke** [comment]
Update
-
- Can now filter anything from the table (except for flexitime checkboxes)
- VL and P status have been changed to 'Vacation Leave' and 'Present'

![image](https://cloud.githubusercontent.com/assets/10201846/9675375/1eb475f2-52ef-11e5-892a-1e37fc345421.png)

Done in my local pc. For Testing on local.
http://16.178.42.181/
-
**All Passwords are: 123**
- **Admin Account:** jin@gmail.com

- **Supervisor Account:** alvincris.uy@hp.com

- **TL Account:**
  - Dev Team: alfredoa.salvadorjr@hp.com
  - Team Robby: mark@gmail.com

- **Agent Account:**
  - Dev Team:
    - christopher.perez@hp.com
  - Team Robby:
    - pogs@gmail.com

**Comment by asjr4584** [comment]
Hi Jin,

Please use the full description for all statuses.

**Comment by lyn2711** [comment]
Passed, test done in 201
