### ISSUE TITLE
Functionality - Dashboard Admin Filter

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#66]
Task
-
- Do not display the Admins and TLs on the Dashboard
- Do not track Admin's attendance (including supervisor, manager, TL, workforce, QA)

**Comment by Jinsuke** [comment]
Update
-
- Dashboard
![image](https://cloud.githubusercontent.com/assets/10201846/9710708/e22ed8c4-556f-11e5-9fe8-d664da6781ff.png)

- Member's Page
![image](https://cloud.githubusercontent.com/assets/10201846/9710713/f11789ee-556f-11e5-87ba-6667289116a8.png)

Done in my local pc. For Testing on local.
http://16.178.42.181/
-
**All Passwords are: 123**
- **Admin Account:** jin@gmail.com

- **Supervisor Account:** alvincris.uy@hpe.com

- **TL Account:**
  - Dev Team: alfredoa.salvadorjr@hp.com
  - Team Mark: marktristan.cruz@hpe.com

- **Agent Account:**
  - Dev Team:
    - christopher.perez@hpe.com
  - Team Mark:
    - reynan.fortes@hpe.com


**THANK YOU @alvincrisuycorel **

**Comment by lyn2711** [comment]
Passed, test done in 181

**Comment by lyn2711** [comment]
Pass, test done in 203

**Comment by lyn2711** [comment]
Pass, test done in 201
