### ISSUE TITLE
Message under Notifications was cut

### ISSUE THREAD

**Issue by lyn2711** [HP-Corel/AttendanceTracker#67]
![image](https://cloud.githubusercontent.com/assets/7370325/9724796/da1ca0e4-560f-11e5-8aa3-166aacb29dd7.png)

**Comment by Jinsuke** [comment]
Update
-
- This is now fixed on my local server. For testing on Local.

![image](https://cloud.githubusercontent.com/assets/10201846/9726517/53c7944c-5626-11e5-9a6c-557888ef3417.png)

http://16.178.42.181/
-
**All Passwords are: 123**
- **Admin Account:** jin@gmail.com

- **Supervisor Account:** alvincris.uy@hpe.com

- **TL Account:**
  - Dev Team: alfredoa.salvadorjr@hp.com
  - Team Mark: marktristan.cruz@hpe.com

- **Agent Account:**
  - Dev Team:
    - christopher.perez@hpe.com
  - Team Mark:
    - reynan.fortes@hpe.com

**Comment by lyn2711** [comment]
Passed, test done in 181

**Comment by alvincrisuycorel** [comment]
Pull in 203

**Comment by lyn2711** [comment]
Passed, test done in 203

**Comment by Jinsuke** [comment]
For testing on 201. 
http://16.178.42.201/
-

**Comment by gigiadamantopoulos** [comment]
passed in 201
