### ISSUE TITLE
Software - Installer with Shortcut creation

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#68]
Task
-
Export the software as a full installer with create shortcut.

**Comment by Jinsuke** [comment]
Update
-
- Created program installer with shortcut.

![image](https://cloud.githubusercontent.com/assets/10201846/9727921/b8d9c908-5636-11e5-8a40-4acdee07ed6f.png)

- For testing by ma'am @lyn2711 .

**Comment by lyn2711** [comment]
Passed, test done in 203

**Comment by Jinsuke** [comment]
For testing on 201. 
http://16.178.42.201/
-

**Comment by Jinsuke** [comment]
Hi @gigiadamantopoulos ,
For testing :grimacing:

**Comment by gigiadamantopoulos** [comment]
Passed in 201
