### ISSUE TITLE
Software Updates Deployment

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#70]
**CURRENT VERSION: Attendance Tracker 1.0**
-

- **Our program should have continuous updates on the fixes/changes**
- Task is to make the program an updater instead of becoming another installer. If a different version is available, the newer version should overwrite the old version.

**Comment by Jinsuke** [comment]
Update
-
- Done on my local computer. Will provide the next update every 15 days as discussed.

**Comment by asjr4584** [comment]
Hi Jin,

Thanks for this. We should release an update twice a month, every 15 days.

Let’s provide an updated installer tomorrow, September 15.

@DevTeam,

Please make sure that the deadlines is fixed and tested prior to the distribution of the updated installer tomorrow.

Regards,
Alfredo “Allan” A. Salvador, Jr.
Team Lead, Customer Solutions Rep V
HP ES Business Process Services

M + 639228901356
E alfredoa.salvadorjr@hpe.com<mailto:alfredoa.salvadorjr@hpe.com>
Hewlett-Packard Philippines Corporation
4th Floor Two World Square Building
22 Upper McKinley Road, Fort Bonifacio,
Taguig City, Philippines 1634
Philippines

[HP]<http://www.hp.com/>

**Comment by asjr4584** [comment]
@DevTeam,

Updated installer must be fully tested before distribution. This Github issue must be regularly updated prior to the distribution.

**Comment by gigiadamantopoulos** [comment]
Passed!
