### ISSUE TITLE
Software - Change aux before pop up warning

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#71]
Task
-
- Task is to let the Aux change before the Warning pop up appears.
- e.g. If I click on Aux 9, time should now run before the Pop up ("Please change Aux 9 to AVAYA") appears.

**Comment by Jinsuke** [comment]
Update
-
- Done on my local computer. Will provide the next update every 15 days as discussed.

**Comment by asjr4584** [comment]
Hi @Jinsuke ,

Can we include this fix in tomorrow’s update?

Please advise.

**Comment by Jinsuke** [comment]
Hi Sir @asjr4584 ,

This will be included in the next version. :)

**Comment by asjr4584** [comment]
Hi Jin,

Can we include this fix in tomorrow’s update?

Please advise.

**Comment by gigiadamantopoulos** [comment]
Passed!
