### ISSUE TITLE
Functionality - Groups Calendar

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#72]
Task
-
- Groups Calendar should also have their own month selection that will load the page every change of months.
- Events should also follow by the month selected.

**Comment by Jinsuke** [comment]
Done in my local pc. For Testing on local.
http://16.178.42.181/
-
**All Passwords are: 123**
- **Admin Account:** jin@gmail.com

- **Supervisor Account:** alvincris.uy@hpe.com

- **TL Account:**
  - Dev Team: alfredoa.salvadorjr@hp.com
  - Team Mark: marktristan.cruz@hpe.com

- **Agent Account:**
  - Dev Team:
    - christopher.perez@hpe.com
  - Team Mark:
    - reynan.fortes@hpe.com

**Comment by gigiadamantopoulos** [comment]
Passed!

**Comment by asjr4584** [comment]
@lyn2711 please test.

**Comment by lyn2711** [comment]
Passed, test done in 203

**Comment by Jinsuke** [comment]
Production 201 testing
-
- Tested on 201 - OK
