### ISSUE TITLE
Functionality - Organization Holiday should reflect on Dashboard

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#73]
Task
-
- Organization Holiday should reflect on Dashboard

**Comment by asjr4584** [comment]
Deploy in 201 Deadline: September 29, 2015

**Comment by alvincrisuycorel** [comment]
Hi Gigi @gigiadamantopoulos 

Please test in 203 :smile:

**Comment by gigiadamantopoulos** [comment]
Passed in 203 and 201

**Comment by asjr4584** [comment]
@lyn2711 for testing in 201.

**Comment by Jinsuke** [comment]
Update
-
- This is related to issue #1 and will be pushed to Production tomorrow - September 30, 2015.

**Comment by lyn2711** [comment]
Passed, test done in 181

**Comment by alvincrisuycorel** [comment]
Merged in 203

**Comment by lyn2711** [comment]
Passed, test done in 203

**Comment by Jinsuke** [comment]
For testing on Production 201 http://16.178.42.201/
-

**Comment by lyn2711** [comment]
Passed, test done in 201

**Comment by Jinsuke** [comment]
Issue

**Comment by gigiadamantopoulos** [comment]
Passed in 181

**Comment by gigiadamantopoulos** [comment]
Passed in 201

**Comment by gigiadamantopoulos** [comment]
Passed in 201
