### ISSUE TITLE
Software: Error Reporting when the app crashes

### ISSUE THREAD

**Issue by alvincrisuycorel** [HP-Corel/AttendanceTracker#75]
Error reporting regarding WPF.

Here are some reference of error reporting that might be useful for this issue.
http://www.codeproject.com/Articles/90866/Unhandled-Exception-Handler-For-WPF-Applications
https://crashreporterdotnet.codeplex.com/
http://www.codeproject.com/Articles/308634/Integrating-Crash-Reporting-into-Your-Application

**Comment by chrisperez** [comment]
Push in github.. Please test. Please ask @Jinsuke for the latest .exe

**Comment by gigiadamantopoulos** [comment]
Passed in 203 and 201

**Comment by asjr4584** [comment]
@lyn2711 for final testing.

**Comment by lyn2711** [comment]
Installed new exe file yesterday, and until today, app has not crashed.  Passed in 201
