### ISSUE TITLE
Error Handling: Filing Two events in one day

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#77]
As discussed with @alvincrisuycorel , please restrict the user in filing 2 events in the same day. An error should be displayed preventing the user to continue...

We must avoid this occurrence in one day

![image](https://cloud.githubusercontent.com/assets/10202106/10128271/a333fbee-65e2-11e5-8625-ddee017f7158.png)

**Comment by gigiadamantopoulos** [comment]
Tested this, functionality wise is Passed... UI needs revision. Please transfer the error message to the Add Event window, please make it red, and please change the message to: " Only one event is allowed to be filed in a day."

![image](https://cloud.githubusercontent.com/assets/10202106/10129572/319ec472-65f2-11e5-8029-ce08f110e27b.png)

**Comment by alvincrisuycorel** [comment]
Hi Gigi @gigiadamantopoulos 

For Testing in 203 :smile:

**Comment by asjr4584** [comment]
@gigiadamantopoulos what is the status of this?

**Comment by gigiadamantopoulos** [comment]
Passed in 203... ready for merging in 201

![image](https://cloud.githubusercontent.com/assets/10202106/10156510/7522a020-66b4-11e5-807e-046c3019bf2f.png)

**Comment by Jinsuke** [comment]
Testing Production 201
-
- Passed! OK! :+1:
