### ISSUE TITLE
Error Handling: No Internet Connection

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#79]
Task
-
- Prevent program from crashing on Start-Up while the computer is still connecting to the internet.

![eee](https://cloud.githubusercontent.com/assets/10201846/10210156/fb486d76-6815-11e5-9c59-2be5d2b61e60.png)

**Comment by Jinsuke** [comment]
Update
-
- Added Error Message to catch error if there's no internet connection.
- This will be added on Attedance Tracker 1.3

![image](https://cloud.githubusercontent.com/assets/10201846/10210801/2f7e4eaa-681e-11e5-9b1c-f65af42cccac.png)

**Comment by gigiadamantopoulos** [comment]
Passed in 201 when you tried logging in but there is no internet..... but I suggest that this message should also appear when you are already logged in.

![image](https://cloud.githubusercontent.com/assets/10202106/10301417/e908ac3e-6c34-11e5-900a-804a5cbe2d6c.png)

**Comment by Jinsuke** [comment]
Update
-
- *Added No Internet Pop up whenever there is a sudden Internet Interruption on the Main Window*
https://cloud.githubusercontent.com/assets/10202106/10301417/e908ac3e-6c34-11e5-900a-804a5cbe2d6c.png

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing please.

**Comment by gigiadamantopoulos** [comment]
Passed in 201
