### ISSUE TITLE
UI - Groups / My Team

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#8]
**NOTE: My Teams tab should be changed to "Groups"**

This page is the main Team Creation Page. This should show where ADMIN users can create TEAMs and Add Team Members

**USER INTERFACE**
* TEAM ID creation
* Team Name creation
* Search field for adding team member
* Team Members list

**FUNCTIONALITY**
* CREATE team
* CANCEL team
* ADD team member

**Reference MockUp**
![image](https://cloud.githubusercontent.com/assets/10201846/8296183/fe7d7d4a-197f-11e5-9655-d8ea7590efea.png)

**Comment by Jinsuke** [comment]
*Add MEMBERS AND CALENDAR TAB
*MEMBERS tab still has the same output
*Add CALENDAR Function that will show users who are on leave (Refer to Outlook's Calendar)

**Comment by gigiadamantopoulos** [comment]
No issues

**Comment by Jinsuke** [comment]
150630 UI UPDATE
![image](https://cloud.githubusercontent.com/assets/10201846/8421844/510529f6-1f06-11e5-9db2-8580fe714f9e.png)

**Comment by gigiadamantopoulos** [comment]
Hi,

Similar to the organization tab, can we make the Group ID auto-generated and un-editable?

![image](https://cloud.githubusercontent.com/assets/10202106/8462710/39a1999e-2068-11e5-9d75-1ab08e392107.png)

**Comment by asjr4584** [comment]
@gigiadamantopoulos if there is no UI issue here, please assign this to @lyn2711 . Please add your functionality comment to the correct GitHub issue.

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Pass, test done on QA server

**Comment by gigiadamantopoulos** [comment]
Passed in 201
