### ISSUE TITLE
Error Handling: Logout Notification

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#80]
Task
-
- Make changes to the log out message to inform the user that the shift will end if the logout button is pressed. Also, if there's a need to close the program, end the program via Task Manager.

**Comment by Jinsuke** [comment]
Update
-
- New Logout Alert for review.

![image](https://cloud.githubusercontent.com/assets/10201846/10211885/9eb00776-682a-11e5-97a4-38e11219845a.png)

**Comment by chrisperez** [comment]
I will handle this one. I need to create a new popup window for this.

**Comment by asjr4584** [comment]
@chrisperez please take note that this is included in the October 15 update release.

**Comment by chrisperez** [comment]
@Jinsuke,

Please pull and create an installer so that @gigiadamantopoulos can test.

**Comment by alvincrisuycorel** [comment]
@Jinsuke 

:smile:

**Comment by Jinsuke** [comment]
Update
-
- Edited New Logout Message.
![image](https://cloud.githubusercontent.com/assets/10201846/10473586/af8cd81e-725f-11e5-8ead-a8aa66c4a9ae.png)

For testing! Installer has been sent on your email!

**Comment by gigiadamantopoulos** [comment]
Passed!

Suggestion though, a space between the two paragraph...

**Comment by Jinsuke** [comment]
For testing.
-
- Updated text.
![image](https://cloud.githubusercontent.com/assets/10201846/10530354/ac0d509e-73d9-11e5-853f-ba890ab02b52.png)

**Comment by gigiadamantopoulos** [comment]
Passed!
