### ISSUE TITLE
Server Setup AttendanceTracker in dev, stage, prod

### ISSUE THREAD

**Issue by alvincrisuy** [HP-Corel/AttendanceTracker#83]

**Comment by alvincrisuycorel** [comment]
![capture2](https://cloud.githubusercontent.com/assets/7260700/10354711/62177400-6d95-11e5-9bf1-508de7d7b61e.PNG)

**Comment by alvincrisuycorel** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu

**Comment by alvincrisuycorel** [comment]
https://help.github.com/articles/generating-ssh-keys/#platform-linux

**Comment by alvincrisuycorel** [comment]
https://www.digitalocean.com/community/questions/copy-ssh-key-to-clipboard

**Comment by asjr4584** [comment]
Deadline: October 15, 2015 (Production)

**Comment by alvincrisuycorel** [comment]
Done in Staging and Dev

**Comment by asjr4584** [comment]
@chrisperez please develop three attendance tracker applications pointing to the following servers:

(1) dev: c9t16755.itcs.hpecorp.net 16.250.43.122
(2) stg: c9t16850.itcs.hpecorp.net 16.250.55.83
(3) prd: c4t16973.itcs.hpecorp.net 16.248.19.91

**Comment by chrisperez** [comment]
Done by @Jinsuke.
