### ISSUE TITLE
Functionality - Groups / My Team

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#9]
**NOTE: My Teams tab should be changed to "Groups"**

This page is the main Team Creation Page. This should show where ADMIN users can create TEAMs and Add Team Members

**USER INTERFACE**
* TEAM ID creation
* Team Name creation
* Search field for adding team member
* Team Members list

**FUNCTIONALITY**
* CREATE team
* CANCEL team
* ADD team member

**Reference MockUp**
![image](https://cloud.githubusercontent.com/assets/10201846/8296183/fe7d7d4a-197f-11e5-9655-d8ea7590efea.png)

**Comment by Jinsuke** [comment]
*Add MEMBERS AND CALENDAR TAB
*MEMBERS tab still has the same output
*Add CALENDAR Function that will show users who are on leave (Refer to Outlook's Calendar)

**Comment by chrisperez** [comment]
- Added filter in Enter User text search field under Add Group Members
- You can search a member by enter the Employee Number, Email, or Name
- Added hyperlink to every group name in the Group List section going to each group's individual pages

**Comment by chrisperez** [comment]
- Change "Enter User" to "Search Member" in Member Search field
- Change "Name" to "Member List"
- Hide Cancel button

**Comment by gigiadamantopoulos** [comment]
Can a member be part of 2 teams at the same time? if not, we should also add a restriction that a member can only be added to 1 team only.

**Comment by Jinsuke** [comment]
Hi @gigiadamantopoulos , yes, a member can only be added once. This will be implemented soon. :)

150630 UI UPDATE
![image](https://cloud.githubusercontent.com/assets/10201846/8421844/510529f6-1f06-11e5-9db2-8580fe714f9e.png)

**Comment by gigiadamantopoulos** [comment]
Hi, 

Is it possible that the members that is already added to the group will not show up to the search member list?

![image](https://cloud.githubusercontent.com/assets/10202106/8462764/a7581a08-2068-11e5-8df0-d8d9a035c052.png)

**Comment by asjr4584** [comment]
@chrisperez assigning this back to you for an answer.

**Comment by chrisperez** [comment]
Done as requested. Please merge and test.

**Comment by gigiadamantopoulos** [comment]
Passed

**Comment by lyn2711** [comment]
Pass

**Comment by lyn2711** [comment]
Pass, test done on QA

**Comment by gigiadamantopoulos** [comment]
passed in 201
