### ISSUE TITLE
Functionality: Gray out the option to file a leave if we no longer have the allocation for a specific date

### ISSUE THREAD

**Issue by gigiadamantopoulos** [HP-Corel/AttendanceTracker#90]
Suggestion from Tara:

Hi Allan, 
Question, can we grey out the option to file a leave if we no longer have the allocation for a specific date?

Thank you,

Tara

**Comment by asjr4584** [comment]
@chrisperez please provide your feedback about this suggestion.

**Comment by chrisperez** [comment]
Duplicate issue #87

**Comment by asjr4584** [comment]
Duplicate
